### ISSUE TITLE
Cannot read property 'success' of undefined

### ISSUE THREAD

**Issue by Toso82** [Foxandxss/angular-toastr#100]
BundleConfig.cs:

bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                        "~/Scripts/jquery-{version}.js"));
bundles.Add(new ScriptBundle("~/bundles/jqueryui").Include(
              "~/Scripts/jquery-ui-{version}.js"));
bundles.Add(new StyleBundle("~/Content/css").Include(
                   "~/Content/bootstrap.css",
                   "~/Content/site.css",
                   "~/Content/themes/base/all.css",
                   "~/Content/css/select2.css",
                   "~/Content/select2-bootstrap.css",
                   "~/Content/select2.css",
                   "~/Content/angular-toastr.css"));
bundles.Add(new ScriptBundle("~/bundles/jqueryval").Include(
                        "~/Scripts/jquery.validate*"));

bundles.Add(new ScriptBundle("~/bundles/modernizr").Include(
                        "~/Scripts/modernizr-*"));

bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include(
                      "~/Scripts/bootstrap.js",
                      "~/Scripts/respond.js"));

bundles.Add(new ScriptBundle("~/bundles/angular").Include(
                       "~/Scripts/angular.js",
                       "~/Scripts/i18n/angular-locale_it-it.js",
                       "~/Scripts/angular-sanitize.js",
                       "~/Scripts/angular-animate.js",
                       "~/Scripts/angular-ui.js",
                       "~/Scripts/angular-toastr.tpls.js"));
------------------------------------------------------------------------------------------------
app.js

 var app = new angular.module('mca', ['ui.select', 'ngSanitize', 'ngAnimate', 'toastr']);
.....

app.controller("McaController", ["$http", function ($http,toastr) {....

....

mca.calcola = function () {
            $http.post('/Home/calcolaMca', {subject:mca.subject,comparable:mca.comparable}).success(function (data) {
                mca.calcolo = data;
               
                toastr.success('Hello world!', 'Toastr fun!');
            });
        }
------------------------------------------------------------------------------------------------

Give me this error:

TypeError: Cannot read property 'success' of undefined
    at app.js:687
    at angular.js:9408
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$eval (angular.js:14466)
    at Scope.$digest (angular.js:14282)
    at Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)
    at XMLHttpRequest.requestLoaded (angular.js:9829)

Where is the problem?

**Comment by Foxandxss** [comment]
The problem is that you're using the array notation for the controller:

```javascript
app.controller("McaController", ["$http", function ($http,toastr) {....
```

That means that for the first parameter, will use the first element of the array, so `$http` will match `'$http'` and the second parameter, `toastr` will match... nothing, you need to add it like:

```javascript
app.controller("McaController", ["$http", "toastr", function ($http,toastr) {....
```

If you don't add it, `toastr` is undefined so if you do a `toastr.success`, you will get a `TypeError: Cannot read property 'success' of undefined`.
