### ISSUE TITLE
Custom Configuration

### ISSUE THREAD

**Issue by Toso82** [Foxandxss/angular-toastr#101]
toastr.success('', '', { positionClass: 'toast-top-full-width' });
Not in correct position.

I try to use also this to inizialize but not enter in function(toastrConfig) 
var app = new angular.module('mca', ['ui.select', 'ngSanitize', 'ngAnimate', 'toastr']);

    app.config(
        function (uiSelectConfig) {
            uiSelectConfig.theme = 'bootstrap';
        },

        function(toastrConfig) {
            angular.extend(toastrConfig, {

                positionClass: 'toast-top-full-width',
            });
        }
    );

**Comment by Foxandxss** [comment]
Check #98, #78 and #73

**Comment by Toso82** [comment]
Ok i read this but how can inizialize positionClass: 'toast-top-full-width' as default without change angular-toastr.tpls.js

**Comment by Foxandxss** [comment]
The README has the proper instructions to do that.

**Comment by Toso82** [comment]
I do this but not work

 app.config(
        function (uiSelectConfig) {
            uiSelectConfig.theme = 'bootstrap';
        },

        function (toastrConfig) {

            angular.extend(toastrConfig, {
                positionClass: 'toast-top-full-width'               
            });           
        }
    );

**Comment by Foxandxss** [comment]
I'm in mobile so I Cant help properly, but i dont think that .config
accepts more than one function.

**Comment by Toso82** [comment]
Ok thanks this is the problem one function work thanks for all
