### ISSUE TITLE
newToast.scope.init is not a function

### ISSUE THREAD

**Issue by gauravbhavsar** [Foxandxss/angular-toastr#102]
TypeError: newToast.scope.init is not a function
    at angular-toastr.tpls.js:166
    at processQueue (angular.js:13248)
    at angular.js:13264
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312
    (anonymous function)           @ angular.js:11655
    $get                                      @ angular.js:8596
processQueue                          @ angular.js:13256
(anonymous function)              @ angular.js:13264
completeOutstandingRequest  @ angular.js:4924
(anonymous function)              @ angular.js:5312

This error only generated when a toaster populated first time only.

I am using your app.config :

below one : 

    app.config(function(toastrConfig) {
      angular.extend(toastrConfig, {
        allowHtml: false,
        autoDismiss: false,
        closeButton: false,
        closeHtml: '<button>&times;</button>',
        containerId: 'toast-container',
        extendedTimeOut: 1000,
        iconClasses: {
          error: 'toast-error',
          info: 'toast-info',
          success: 'toast-success',
          warning: 'toast-warning'
        },
        maxOpened: 0,    
        messageClass: 'toast-message',
        newestOnTop: true,
        onHidden: null,
        onShown: null,
        positionClass: 'toast-top-right',
        preventDuplicates: false,
        preventOpenDuplicates: false,
        progressBar: false,
        tapToDismiss: true,
        target: 'body',
        templates: {
          toast: 'directives/toast/toast.html',
          progressbar: 'directives/progressbar/progressbar.html'
        },
        timeOut: 5000,
        titleClass: 'toast-title',
        toastClass: 'toast'
      });
    });

**Comment by Foxandxss** [comment]
Please, try to replicate it on http://plnkr.co/edit/tpl:nKLNBdve51sqOoKZAOUS

And you don't need to use my config. It is being used by default. You just need to override some properties if needed.

**Comment by gauravbhavsar** [comment]
@Foxandxss Thanks for help.

I remove config file and now its working.

and override properties like :

    toastr.success('Hello world!', 'Toastr fun!', {
                        timeOut: 2000,
                        closeButton: true
                    });

it is very useful great work.
many thanks.

Sorry for created new issue.
