### ISSUE TITLE
Close displaying toaster error messages if URL is changed

### ISSUE THREAD

**Issue by mehmedju** [Foxandxss/angular-toastr#103]
Hi guys,

I have applied this directive into my project. Here is an example:

  toastr.error("X", "Y", {
                                    closeButton: true,
                                    timeOut: 0,
                                    tapToDismiss: false,
                                });

When I open some other page within same project, it is being showed all time. How can I remove it if URL is changed ?

Thanks,

**Comment by Foxandxss** [comment]
Since your toasts are sticky, what you could do is set a listener for route changes. If you're using ngRouter you could do something like:

```javascript
app.run(function($rootScope, toastr) {
  $rootScope.$on('$routeChangeSuccess', function() {
    toastr.clear();
  });
});
```

That will clear any opened toasted every time you change your routes.

**Comment by mehmedju** [comment]
It works perfectly. Thanks a lot @Foxandxss
