### ISSUE TITLE
Can't use in interceptors

### ISSUE THREAD

**Issue by nmnandakishore** [Foxandxss/angular-toastr#106]
As toastr has $http dependency via $templateRequest, its returning Circular dependency error.

Providing option to remove $templateRequest dependency like enabling it only when custom templates are assigned (In-line default template) might be an option.

![capture123](https://cloud.githubusercontent.com/assets/4891407/8031134/b295f412-0de9-11e5-8e7c-8ac5b01e7eb0.JPG)

**Comment by Foxandxss** [comment]
When are you finding this error? I would like to reproduce it.

**Comment by nmnandakishore** [comment]
Please use this interceptor


```javascript

app.factory('SampleInterceptor', ['$q', 'toastr', function($q, toastr){

    var service = {}

    service.response = function(response){
        console.log('@interceptor->response');
        console.log(response);
        toastr.success(response.data.message, 'Success');
        return response;
    }

    return service;
}])

```

**Comment by Foxandxss** [comment]
So, I can't remove `$templateRequest` because I am not using it. `$templateRequest` is being used internally by the directives.

The workaround for this kind of stuff (this error is waaay common in angular) is to load the problematic dependency (toastr in this case) in run time. Try something along this lines:

```javascript
app.factory('SampleInterceptor', ['$q', '$injector', function($q, $injector){

    var service = {}

    service.response = function(response){
        var toastr = $injector.get('toastr');

        console.log('@interceptor->response');
        console.log(response);
        toastr.success(response.data.message, 'Success');
        return response;
    }

    return service;
}])
```

That should do the trick. And yes, put the `$injector.get()` in the inner function, so it will required at runtime when a request is done.

**Comment by nmnandakishore** [comment]
Thanks Foxandxss, the trick worked for me..

**Comment by Foxandxss** [comment]
Good. It is a common workaround in Angular. It is not an issue with my library. There are some stuff in Angular like interceptors and error handlers that are really really picky with injections.

**Comment by nmnandakishore** [comment]
:+1:

**Comment by samirfor** [comment]
I needed to understand the functioning of interceptors reading [this article](http://www.webdeveasy.com/interceptors-in-angularjs-and-useful-examples/) to get to my solution:


```javascript
angular.factory('responseErrorInterceptor', ['$q', '$injector', function($q, $injector){
    var service = {}

    service.responseError = function(responseError){
        if (responseError.status >= 500 && responseError.status < 600) {
            var toastr = $injector.get('toastr');
            toastr.success('Oops, server looks like down.', responseError.statusText);
        }
        return responseError;
    }

    return service;
}]);
```

This worked for me. Thanks @Foxandxss
