### ISSUE TITLE
Access to template scope

### ISSUE THREAD

**Issue by danielbsig** [Foxandxss/angular-toastr#108]
Hi,

I'm fiddling with a custom toast which displays some HTML. In fact, the HTML is some angular code - I'm displaying an undo button, and that code needs information about what to undo when the button is pressed (it should work similar to what happens in Gmail when an operation is performed there, and the user is given the option to undo the operation when the success notification appears).

What I would like is some way for me as the caller of toastr.success(), to pass in some data what will be accessible in the scope in my custom template. This could be just a single object which I could then populate at will. The code would simply put it in the scope object, and then forget about it. 

Yes I'm aware that it would be possible to use parent scope tricks, but it would both be very dirty, as well as fragile, since it could easily break if two toasts were to be displayed, one after the other, and the data for the second toast would override the data for the first one.

On a side note, is there any reason why it is not possible to choose the toast template on a per-toast basis? In my case, the default template would suffice in most cases, but I would only need my custom template in the particular scenarios when I need to display the undo button, which is only in some cases.

Regards,
Daníel

**Comment by Foxandxss** [comment]
Well, `angular-toastr` doesn't allow angular on it. I decided to do that for security reasons.

The actual implementation doesn't allow a template per toast but that is a feasible option (but I don't see it useful as today).

I mean, if you need to add a button, add it as the message, you don't need to create a completely new template for that.

```javascript
toastr.success('<button>This is a button</button>', {
  allowHtml: true,
  onHidden: function(clicked) {
    if (clicked) {
      // do something
    }
  }
});
```

Something like that could work, but sadly allowing Angular to run inside toasts was a bit risky.

**Comment by danielbsig** [comment]
This would be an option, but again, having a button without any actual logic behind it is a bit useless. Since this is an Angular app, why not have a button with a ng-click? I tried adding a button with the ng-click attribute to the message, but it isn't compiled by Angular and didn't work.

The support for a different template is there anyway, which is a good thing since it allows for more DRY implementations. I think in both cases (i.e. per-toast template, and custom data with each toast) this would be an improvement. Well, at least in my case :-)

Both of these were something I could work around - a) by injecting the toastrConfig object into my own service which encapsulates your service and b) by hardcoding the title in my own template and use the "title" property for my custom data, but these solutions are rather dirty. I would prefer something cleaner.

**Comment by Foxandxss** [comment]
The problem with allowing angular on the toasts is that I would need to rewrite some of the directives to allow html in a way that it could accept anything, anything at all. That includes XSS and you name it.

I will study both things (angular on toasts and per-toast template).

**Comment by danielbsig** [comment]
You *are* already allowing angular in the toast, since you are already supporting custom templates. I can add the following to my custom template: <a ng-href="doStuff()">Do stuff</a>, and then somewhere, for instance somewhere in the module definition, inject $rootScope and specify $rootScope.doStuff = function doStuff() { etc. }

The only problem with this approach is that there is no way to pass in data to the function in the template (unless by cheating, as I did), since the template only has access to the scope created for the toast (well, and data on the $rootScope, but that would be a disaster waiting to happen since it would break if I had two toasts displayed one after the other, with different data set to a given $rootScope variable, then the second one would override the first one).

**Comment by Foxandxss** [comment]
Yes, you can do that with custom templates, but I meant passing angular code via message or title.

What would you like to see? I always consider all options :)

**Comment by danielbsig** [comment]
What I would like to see is a fourth parameter to the success function (well, probably all of them), and this variable would be added to the scope of the toast. That way, I can let my template access that variable (it could be a complex object), and - in my case - pass that data to the undo function. Something like this:

    function success(message, title, optionsOverride, customData) {
      var type = _getOptions().iconClasses.success;
      return _buildNotification(type, message, title, optionsOverride, customData);
    }

Etc., that variable would be passed down the chain, until:

      function createScope(toast, map, options) {
        // Code skipped for clarity...
        toast.scope.toastType = toast.iconClass;
        toast.scope.toastId = toast.toastId;
        toast.scope.customData = map.customData; // This line added

I could then access the customData variable in my template, and pass that data to my button ng-click handler (or whatever event handler I'm adding to the template).

The ability to change template on a per-toast basis is another issue altogether :-)

**Comment by mrzepinski** [comment]
@Foxandxss It will be nice to add an OPTION to to that :) +1 for this feature.
You can enable it in .config section, using provider. By default it will be working like today.

**Comment by Foxandxss** [comment]
This is definitely coming soon.

I plan in writing a 2.0.0 version which will be a complete rewrite in ES6 with extra features and this is one of those.

**Comment by parer800** [comment]
When is this planned to be implemented? (date-wise)
I'm currently thinking about writing a workaround for this. 
In my case, we have externalized strings containing scope variables on the server. These variables are inserted with angular's $interpolate, which works fine. What I want to do is to have dynamic `ui-sref` in <a> or with ng-click logic. 

Or is this possible in an other way? without the `onHidden`? because users should be able to close message or go to the link inside it.

**Comment by Foxandxss** [comment]
@danielbsig @mrzepinski @parer800 Could you please check the latest version on master (copy the files on `/dist`) and tell me if that is what you expect? If so I will push a new version later tonight.

**Comment by Foxandxss** [comment]
Ah, forgot to explain how (it is in the README tho).

there is a `extraData` param you can put in the `toastConfig` (global) or put a `extraData` key on the overriding options (to override per toast).

**Comment by danielbsig** [comment]
Seems fine, although I haven't tried using it yet. But definitely looks promising.

**Comment by parer800** [comment]
Awesome (if it works ;) ) thanks for quick response. I will request a new version at 
[webjars](http://www.webjars.org/) so I can test it!
Guessing that will take one day maybe

**Comment by mrzepinski** [comment]
@Foxandxss Looks nice. I will try it. Thanks :)

**Comment by parer800** [comment]
@Foxandxss will you create a new release with this soon?

**Comment by Foxandxss** [comment]
As soon as you guys confirms that this is what you need and I revise a new PR. This weekend for sure.

**Comment by Foxandxss** [comment]
New version is up!

**Comment by lebolo** [comment]
Is `extraData` only accessible within the template? I was trying to do something like:

```javascript
toastr.warning('<button type="button" class="btn btn-primary" onClick="extraData.foo()">Do Foo</button>', 'Foo Title', {
    allowHtml: true,
    timeOut: false,
    extendedTimeOut: 10000,
    tapToDismiss: false,
    extraData: {
        foo: function() { // do something }
    }
});
```

But nothing happens on click.

**Comment by Foxandxss** [comment]
@lebolo Yes, only inside the template. As today I don't offer angular code inside message / title because I decided back in the day that it was a security issue. I will research that again for 2.0.0.

**Comment by lebolo** [comment]
Thanks @Foxandxss, that makes sense.

**Comment by pdesgarets** [comment]
Hi @Foxandxss, I came across the same need (use angular variable in the message) and I don't really see how it is more risky than using angular variables in a template. I may be missing something, but it seems to me that the message given at the creation of the toast is just an easy way not to have to rewrite the whole template. One could as easily use variables from a user input in the template than in the message, and I think it is up to each developer to sanitize user inputs.

**Comment by umdstu** [comment]
+1, would love to have a button that does something inside a toast. Currently clicking it closes it and sends you to the root path.

**Comment by dgodwin1175** [comment]
Hi @Foxandxss, can you give an example of how the extraData would be used to say, handle an ng-click event?  For example, if I want to add a link to my template like this:
<a href="#" class="link" ng-click="clickFn(data)">Link Text</a>

And I want to provide all of the variables in this link in the extradata, would it look like this:
myData.LinkClass = "link";
myData.LinkFn = "clickFn";
myData.FnData = data;
myData.LinkText = "Link Text";

this.toastr.error(message, title, { extraData: myData });

<a href="#" class="{{extraData.LinkClass" ng-click="??">{{extraData.LinkText}}</a>

Thanks!

**Comment by ng-parth** [comment]
Hi @Foxandxss @dgodwin1175, 
Any updates on weather this thing is achieved and available??
