### ISSUE TITLE
Please provide a .scss file

### ISSUE THREAD

**Issue by Paul-Todd** [Foxandxss/angular-toastr#114]
I would like to integrate this into ionic and it should be trivial if you could provide the .scss file.

Is this possible? I would happily contribute back the file with integrations into the ionic framework

**Comment by Foxandxss** [comment]
I don't have any .scss file.

**Comment by Paul-Todd** [comment]
Thanks for the prompt respose - I ended up wrapping some scss over the css to create the effect I needed. I will put up the fixes later on my repo. This is a really cool and easy way to add toasts to the ionic framework - congratulations on such a good job!

**Comment by Foxandxss** [comment]
Yeah, sorry for not having a .scss file. Once you pick one (less or scss) it is better to stick with it :)
