### ISSUE TITLE
Can't have onHidden callback function working

### ISSUE THREAD

**Issue by timtim-75** [Foxandxss/angular-toastr#115]
Hi, 

Amazing work on this.
I'm trying to put all my toasts in a Json file to make my code clean. So I'm parsing the Json and trying to call an onHidden callback function but I don't know how to do it, there is no exemple on the read me section.
Could you make my day and give me some advice ?

Thanks a lot

**Comment by Foxandxss** [comment]
the third parameter of a toast is an object, you can pass a function under "onHidden" which will be called when a toast is hidden.

If you don't make it work, please create a plunker to show how to use i t.

**Comment by timtim-75** [comment]
The problem seems to come from my JSON : 
If I do that code in my js file, it works like a charm and I'm receiving true on click
toastr.info('foo', "bar", { 
    onHidden:function(click){
        console.log(click);
    }
 });
but I'm in a JSON file so, its a string, not evaluated by the file.

Have you any idea if I can make it work in a JSON way, or should I abandon this idea and make all my toasts in my functions ?

Thanks a lot.

**Comment by Foxandxss** [comment]
I don't know what are you doing.
