### ISSUE TITLE
Buggy animations (Open, Close, TimeOutClose, etc)

### ISSUE THREAD

**Issue by aosi87** [Foxandxss/angular-toastr#118]
Hi, first, great module really great.

Now, i got angular 1.2.28, ngAnimate 1.2.28 too, now when i add this dependencies inside my MEAN stack project i can see the toast appear, but the animations (fade) works just on the first notification, also if i change some options like progressBar doesn't seems to work, i'm sure ngAnimate works 'cause am using ui-view tag with animation transitions.

I read the CSS looks fine, change the templates to show progressBar template, but still doesn't work.

EDIT.- I just find out that progressBar option (support) doesn't exist in version 0.4.x, sorry to bother you =D cheers. But the buggy animations are a real thing =D so i will change the title.

The animations that look funny are, when you create a toastr the first time looks great awesome and right, but if i create more, those toastr doesn't show animations, on close looks buggy, when timerout looks buggy.

**Comment by Foxandxss** [comment]
Hello,

This library needs angular 1.3+.  there is an old version in a branch but
doesn't have that many features.

**Comment by Foxandxss** [comment]
I would need to see a plunker for that.

**Comment by aosi87** [comment]
I'm using that one (0.4.X), well i think i will do a fork and work some solutions =D. i hope this doesn't bother you. Cheers.
