### ISSUE TITLE
Animations only for the first toast

### ISSUE THREAD

**Issue by razvanz** [Foxandxss/angular-toastr#121]
I don't get animations for any toasts after the fist one. Upon inspection it seems that the animation classes are not added.

The config:

```javascript
{
        autoDismiss: true,
        extendedTimeOut: 3000,
        maxOpened: 2,
        newestOnTop: true,
        positionClass: 'toast-top-full-width',
        preventOpenDuplicates: false,
        tapToDismiss: true,
        templates: {
          toast: 'app/templates/toast.html'
        },
        timeOut: 5000
}
```

`angular: 1.4.4`

**Comment by Foxandxss** [comment]
Can I have a reproduction in a plunker?

**Comment by razvanz** [comment]
There's the [plunker](http://plnkr.co/yaS654g8SpOQwxyCof5K). The behavior seems not to be influenced by the options. It's default. With default style / animation it isn't that noticeable, but it becomes an issue when customized.

**Comment by Foxandxss** [comment]
I see that, it only happens on 1.4.4. Will check.

**Comment by Foxandxss** [comment]
@razvanz Seems like it is a bug and it will be fixed for 1.4.5

**Comment by razvanz** [comment]
Great :+1:

**Comment by aosi87** [comment]
Same here but on branch for angular 1.2.X

**Comment by Foxandxss** [comment]
@aosi87 I would need to see that in a plunker.

**Comment by Foxandxss** [comment]
1.4.5 is out so this should be fixed. If there is still a 1.2.x bug I would like a new issue with a repro.

**Comment by eliashdezr** [comment]
Getting this issue with Angular v1.4.9

**Comment by Foxandxss** [comment]
I need a repro and put it on a new issue.

Thanks.
