### ISSUE TITLE
Custom tap function

### ISSUE THREAD

**Issue by mrzepinski** [Foxandxss/angular-toastr#123]
I would like to call my function when user tap on toast. Is there any option for that?
I don't want to override all templates. Just one toast has to have custom action on tap.

And one more. I know that I can define onShown or onHidden function, but I want to have sticky toast with custom tap function which cannot close my toast.

**onTap** - **null** by default, function to invoke when user tap on toast

**Comment by mrzepinski** [comment]
https://github.com/Foxandxss/angular-toastr/pull/124

**Comment by Foxandxss** [comment]
Let's continue there then.
