### ISSUE TITLE
Overriden options

### ISSUE THREAD

**Issue by vkozyref** [Foxandxss/angular-toastr#126]
Why I cannot owerride some options eg positionClass?
var badOptions = ['containerId', 'iconClasses', 'maxOpened', 'newestOnTop',
                            'positionClass', 'preventDuplicates', 'preventOpenDuplicates', 'templates'];
          for (var i = 0, l = badOptions.length; i < l; i++) {
            delete options[badOptions[i]];
          }

**Comment by vkozyref** [comment]
var badOptions = ['containerId', 'iconClasses', 'maxOpened', 'newestOnTop',
                            'positionClass', 'preventDuplicates', 'preventOpenDuplicates', 'templates'];
          for (var i = 0, l = badOptions.length; i < l; i++) {
            delete options[badOptions[i]];
          }

**Comment by Foxandxss** [comment]
`positionClass` doesn't belong to the toasts, it belongs to the container. You set what position you want the container to live in, and all toasts appears on that position. It is something that you can't control per toast.

The same applies to the other options, they belong to the container.

I will update the README to be more precise, I get this issue like every month.

For 2.0.0 I will try to bring multiple containers so you can override the position by class.
