### ISSUE TITLE
angular-toastr is show only box content don't have content 

### ISSUE THREAD

**Issue by avatarr** [Foxandxss/angular-toastr#133]
![screen shot 2558-10-23 at 15 09 21](https://cloud.githubusercontent.com/assets/1640817/10687562/33553bde-7998-11e5-9f8e-f70793a87c5e.png)

In above image I try to call toastr and result is not showing 

my code :  toastr.success('Hello world!', 'Toastr fun!');

**Comment by Foxandxss** [comment]
Weird. Are you loading the .css? And if so, can you create a plunker?

**Comment by avatarr** [comment]
Thank you I can solved because I load angular-toastr.min.js not angular-toastr.tpls.min.js

**Comment by Foxandxss** [comment]
Yeah, the non tpls version is not containing any template :)
