### ISSUE TITLE
i found this lib has two directive without specifying namespaces

### ISSUE THREAD

**Issue by e-cloud** [Foxandxss/angular-toastr#135]
i used an extension to view my ng-app's dependencies graph. Then i found this lib has two directive without specifying namespaces —— `progressBar` and `toast`. 
Normally, a third library ought to manage it own dependencies  with specifying namespaces to avoid dependencies conflicts.
So, i think this is an urgent thing to fix!

**Comment by Foxandxss** [comment]
I know I know, I had to add prefixes to lot of directives in ui-bootstrap in the past month. I want to update this library to 2.0.0 with lot of new ideas and prefixes, but I will be really really busy the next month with ui-bootstrap 1.0.0 so this will have to wait sadly.
