### ISSUE TITLE
Access toast in custom callbacks

### ISSUE THREAD

**Issue by TristanPouliquen** [Foxandxss/angular-toastr#138]
Hi,

I'm actually implementing this library that works like a charm and gives great visual results !

My problem is : 

I want to create a toast whenever a user removes one item to give him the chance to undo this deletion for some time by tapping on the toast (via the onTap callback).

However, I haven't found a way to pass to my callbacks which toast was tapped, or to access the toast list and do a custom function that parses them all to find mine (based on content for example) [a much less satisfying option].

Is there a way to access which toast was clicked ? (I haven't found it in my searches in your code)

**Comment by Foxandxss** [comment]
Not really sure I follow. Could you please write some code (in here or a gist) of how would you like to use this feature? Or perhaps explain this with more code.

Thanks.

**Comment by TristanPouliquen** [comment]
Hi, 

thanks for the quick answer. 

Actually, the onTap callback is executed without arguments : 

```
scope.tapToast = function () {
  if (angular.isFunction(scope.options.onTap)) {
    scope.options.onTap();
  }
  if (scope.options.tapToDismiss) {
    scope.close(true);
  }
};
```
What I wanted was to access the tapped toast in the callback, something like this : 

```
scope.tapToast = function () {
  if (angular.isFunction(scope.options.onTap)) {
    // Pass the toast (or anything to retrieve the toast) to the callback function
    scope.options.onTap(toast);
  }
  if (scope.options.tapToDismiss) {
    scope.close(true);
  }
};
```

My problem was : 

Imagine you have a list : 
+ a
+ b
+ c
+ d

The user deletes a,b and c rapidly. I wanted to give the user the possibility to undo this deletion (by showing a toast for each deletion that cancels the deletion on tap).

At first, I only could do this for the last deleted item (saving it into my scope etc), which was a problem in the case of multiple simultaneous deletions.

I was able to isolate each toast, to link each toast to one list item through a separate function : 

``` 
$scope.remove = function(index) {
  var item = $scope.items[index];
  $scope.items.splice(index, 1);
  $scope.deletedItem = item;
  showDeletionToast(item);
};

function showDeletionToast(item) {
  dbService[$scope.collection].remove({ _id: item._id });
  toastr.warning('Cliquez ici pour annuler la suppression de : ' + item.description, 'Suppression', {
    closeButton: true,
    progressBar: true,
    timeOut: 10000,
    onTap: function() {
      var deletedItem = angular.copy(item);
      dbService[$scope.collection].insert(deletedItem, function(err, newDoc) {
        $scope.items.push(newDoc);
        $scope.$apply();
      });
     }
  });
};
```

**Comment by Foxandxss** [comment]
Sounds like you workaround it pretty well, still, I will fix that.

**Comment by TristanPouliquen** [comment]
Thanks, I'm not an expert in JS so I'll let decide what is the cleanest way to do so !

Anyways, great job on this library !

**Comment by Foxandxss** [comment]
Fixed it, will push a release in a bit.
