### ISSUE TITLE
positionClass toastr and materializecss doesn't work

### ISSUE THREAD

**Issue by donnygunawan** [Foxandxss/angular-toastr#139]
positionClass does not work when i use materializecss.com, how to make it work?

**Comment by Foxandxss** [comment]
Create a plunker so I can see it. There is no relation with those two things. I guess you're trying to override positionClass per toast and that is not possible atm.

**Comment by donnygunawan** [comment]
http://plnkr.co/edit/jZS3j73WsexT3Of6SpA0?p=preview

yes i has override, but not work

**Comment by Foxandxss** [comment]
You cannot do that. Position is only for the container, not for the toasts. It has nothing to do with materializecss, it is just a limitation in how toastr work. I will fix that for version 2.0.0
