### ISSUE TITLE
0.4.3 requires "angular: '>=1.3.0'"

### ISSUE THREAD

**Issue by haruyama** [Foxandxss/angular-toastr#143]
https://github.com/Foxandxss/angular-toastr/blob/0.4.3/bower.json
```
...
  "version": "1.6.0",
...
    "angular": ">=1.3.0"
...
```

**Comment by Foxandxss** [comment]
Oh, it created that tag from master, that is wrong indeed. Will have to fix it

**Comment by Foxandxss** [comment]
Created 0.4.4, forgot to bump bower there, but it doesn't really care. If it is a problem for you, please re-open an issue.
