### ISSUE TITLE
positionClass in parameters not overriding defaults

### ISSUE THREAD

**Issue by pelted** [Foxandxss/angular-toastr#146]
**Expected behavior**:

When providing a `positionClass` property on the parameters object it should override the default `positionClass` like the other properties do.

**What actually happens**:

The `positionClass` remains the default of `toast-top-right` or whatever class was passed to `toastrConfig`.

**Examples**:

:link: [plnkr example](http://embed.plnkr.co/6FQHPkLFBEwrdDhAmheG/preview)

```javascript
var app = angular.module('plunker', ['toastr']);

app.config(function(toastrConfig) {
  angular.extend(toastrConfig, {
    positionClass: 'toast-top-right'
  });
});

app.controller('MainCtrl', function($scope, toastr) {
  $scope.showDefaultToast = function() {
    toastr.success('This toast uses default settings', 'Default Settings!')
  };
  
  $scope.showCustomToast = function() {
    toastr.error('This toast should be in the top-left', 'Custom Position!', {
      positionClass: 'toast-top-left'
    })
  };
});
````

**Comment by pelted** [comment]
Umm, I just realized that in `cleanOptionsOverride()` the `positionClass` is getting removed from the override options. Is there something behind the thinking of this that I'm missing?

**Comment by romanmandryk** [comment]
+1
trying to achieve single toast with { positionClass: 'toast-top-full-width'}, while I need my defaults to be toast-top-right. Not possible right now.

**Comment by Foxandxss** [comment]
I get this issue every month heh. As you said, `positionClass` is to override the position on the container. The container is who decide where to put the toasts, so you can override it there.

For the time being, you can inject the config in a service / controller and change it there, but every change of position will only take place after all toasts are closed and the container is re-created.

This is certainly a limitation, but to change that I would need to rewrite quite a lot.

I don't have too much time lately, sadly, but I want to make a 2.0.0 release with a bunch of features, included this one.
