### ISSUE TITLE
Support for AngularJS 2

### ISSUE THREAD

**Issue by juergenzimmermann** [Foxandxss/angular-toastr#148]
It would be fine to have angular-toastr also for AngularJS 2.

**Comment by Foxandxss** [comment]
Indeed, but there are a couple of things to figure out with angular to make that feasible.

I am team lead on ui-bootstrap and ng-bootstrap (the port to angular 2), so as soon as we figure out how some stuff, I will tackle a port.

**Comment by juergenzimmermann** [comment]
Thank you very much for your efforts!

**Comment by derekshi** [comment]
I cannot find any resources on the web so I quickly wrote our own. https://github.com/PointInside/ng2-toastr

**Comment by scttcper** [comment]
I've also written an implementation for angular 2 https://scttcper.github.io/toastr-ng2/

**Comment by Foxandxss** [comment]
I want to work on this after RC6 or final. Which is when a really needed feature to do Toastr is introduced.
