### ISSUE TITLE
dependency issue on angular-animate 1.4.8

### ISSUE THREAD

**Issue by rcholic** [Foxandxss/angular-toastr#149]
I have been using `angular-toastr` in my project for more than a year without any problem, however, I ran into the following injection issue after a **bower update** today:

`Uncaught Error: [$injector:unpr] Unknown provider: $$asyncCallbackProvider <- $$asyncCallback <- $animate <- toastr <- PromiseTimeoutService <- UserService`

After the update, I now have both angular-animate and angular at version 1.4.8. I have a `UserService` that depends on `PromiseTimeoutService`, and the `PromiseTimeoutService` depends on the `toastr` service. I guess this error might be due to some compatibility issue between `angular-animate v1.4.8` and `angular-toastr`, but I am not 100% sure. Could the author of this project take a look and possible apply a patch?

Thanks

**Comment by Foxandxss** [comment]
Uhm, not sure if Angular 1.4.8 broke something. Could you pretty please create a plunker with angular (and ngAnimate) 1.4.8 and this library?

Thank you for reporting this issue.

**Comment by Foxandxss** [comment]
I just tested it and it works with 1.4.8 and 1.5.0-rc.0
