### ISSUE TITLE
clearing a single toast

### ISSUE THREAD

**Issue by saaqibz** [Foxandxss/angular-toastr#152]
I'm trying to figure out how to assign a single toast so that I could clear it. I saw in your sample code you assigned it as the return statement. I tried it as follows:

```
var toast = toastr.info('Stay on this page until uploads complete','Upload Started...',
				{timeOut: 5000, progressBar:true});
$log.debug(toast);
```

However, the log statement returns undefined. Any idea how I could set it up capture a toast object and dismiss a single toast?

**Comment by Foxandxss** [comment]
Works for me http://plnkr.co/edit/bhCMnliEPbryrVmeoihD?p=preview

**Comment by saaqibz** [comment]
I reviewed my code and it looks like I did not put a return in my $decorator. I am unable to test it right now but this is probably it. Thanks for checking, and thanks for this great product.
