### ISSUE TITLE
Current build in /dist seems outdated

### ISSUE THREAD

**Issue by grubersjoe** [Foxandxss/angular-toastr#155]
I wanted to use the documented `toastr.active()` method. Unfortunately this results in an error, because the methode isn't defined in the current build. I checked `dist/angular-toastr.js` and there is indeed no such public function.

After rebuilding with gulp it works correctly. So I guess the `dist` directory is simply outdated.

**Comment by Foxandxss** [comment]
Oh, it is not released.

I wanted to do something else before I make a release and that something else wasn't a good idea after all and then I forgot I had something hanging. I will release right now.

Thanks for the head up.

**Comment by Foxandxss** [comment]
Done, thanks again.
