### ISSUE TITLE
Preserve HTML

### ISSUE THREAD

**Issue by realph** [Foxandxss/angular-toastr#157]
Is there a way to preserve HTML tags with this plugin? I want to have `<strong>` tags around certain bits of my text. But this prints out my tags instead of having a bolder piece of text:

            toastr.success('New user <strong>John Doe</strong> added!');

Any help with this would be appreciated. Thanks!

**Comment by Foxandxss** [comment]
It is all in the readme.

**Comment by realph** [comment]
@Foxandxss Sorry I couldn't see it, mind pointing me in the right direction?

**Comment by Foxandxss** [comment]
you need to set `allowHtml` in the options.

**Comment by realph** [comment]
So, even when I set `allowHtml` it prints my `<strong>` tags. Any idea why this won't work?

**Comment by Foxandxss** [comment]
I need a plunker reproduction

**Comment by realph** [comment]
@Foxandxss http://plnkr.co/edit/GkTiTn2OD9ZzgYv1PEuA?p=preview

**Comment by Foxandxss** [comment]
Ohh, I didn't read the custom template part. Yes, you need `ng-bind-html` to allow HTML stuff on it.

**Comment by realph** [comment]
@Foxandxss That's done the trick. Thanks!

**Comment by tushartrantor** [comment]
@realph, @Foxandxss  : Can you please give me example how can i use it in my case to allow html tags but dont want to have XSS attack. I am not using `$templateCache`. `allowHtml:true`  solves my problem but want to have attack proof.
