### ISSUE TITLE
Circular dependency found

### ISSUE THREAD

**Issue by hexwit** [Foxandxss/angular-toastr#160]
I am injecting service into http interceptor. Service has dependency on toastr.
Angular gives me following error: 

Error: $injector:cdep
`Circular dependency found: $http <- $templateRequest <- $$animateQueue <- $animate <- toastr <- NotificationService <- HttpErrorsInterceptor <- $http <- $templateFactory <- $view <- $state`

Could you suggest how to solve this problem? 

Thanks.

**Comment by Foxandxss** [comment]
Yes, you need to inject it at runtime. There are certain places in angular, one of them being a http interceptor that are really picky with dependencies (not a toastr problem).

You need to inject `$injector` and inside the function you want (request, response...) you can do:

```
var toastr = $injector.get('toastr');
```

And then use it.

**Comment by hexwit** [comment]
I am trying, but no luck. Here is my code: 

Notification service:
```
(function () {
    "use strict";

    angular.module("app.common").factory("NotificationService", ["$injector", NotificationService]);

    function NotificationService($injector) {
        var toastr = $injector.get('toastr');

        var success = function (title, message) {
            toastr.success(title, message);
        };

        var error = function (title, message) {
            toastr.error(title, message);
        };

        return {
            success: success,
            error: error
        };
    }
})();
```

My http error interceptor: 
```
(function () {
    "use strict";

    angular.module("app.common").factory("HttpErrorsInterceptor", ["NotificationService", HttpErrorsInterceptor]);

    function HttpErrorsInterceptor(NotificationService) {
        return {
            requestError: function (request) {
                return request;
            },

            responseError: function (response) {
                return response;
            }
        }
    }
})();
```

I'd like to use toastr inside notification service, and inject service everywhere i need instead of 
injecting toastr directly. Is this possible? Or may be I don't understand something.

**Comment by Foxandxss** [comment]
Oh, I see.

Revert notificationService as you had it before and rewrite the interceptor like:

```javascript
(function () {
    "use strict";

    angular.module("app.common").factory("HttpErrorsInterceptor", ["$injector", HttpErrorsInterceptor]);

    function HttpErrorsInterceptor($injector) {
        return {
            requestError: function (request) {
                var ns = $injector.get('NotificationService');
                // work with it
                return request;
            },

            responseError: function (response) {
                var ns = $injector.get('NotificationService');
                // work with it
                return response;
            }
        }
    }
})();
```

This is a common issue with interceptors. As soon as you require on it a service that requires $http (directly or a children), you need to inject it by hand. There are other problematic services apart from $http.

**Comment by hexwit** [comment]
It is working :) Thank you!
