### ISSUE TITLE
Error: toastr.error is not a function

### ISSUE THREAD

**Issue by txssseal** [Foxandxss/angular-toastr#163]
I keep getting this error `Error: toastr.error is not a function` when trying to launch a toastr.  It works everywhere else in my app but this controller.  Am I doing anything wrong with the setup?

```javascript
(function() {
'use strict'
  angular
    .module('sessions.controller', [
      'ngAnimate',
      'toastr'
    ])
})()
```

```javascript
(function() {
  'use strict'

  angular
    .module('sessions.controller', [])
    .controller("UserSessionsController", UserSessionsController)

  UserSessionsController.$inject = ['$scope', '$auth', 'toastr']

  function UserSessionsController($scope, toastr){
    $scope.$on('auth:login-error', function(ev, reason) {
      toastr.error('Your credentials are gone', 'Error')
    })
  }
})()
```

**Comment by Foxandxss** [comment]
A couple.

First, you are creating a a module `sessions.controllers` with some dependencies (ngAnimate and toastr) then in the second snippet you are re-creating the module (overriding the previous one). To fix that you need to remove the second parameter (the []) on the second module.

Second, you are injecting `['$scope', '$auth', 'toastr']` but in the controller you only have `$scope` and `toastr`. `toastr` in that case is actually `$auth` and it doesn't have that `.error` method you are looking for.

**Comment by txssseal** [comment]
actually forgot I added that module declaration, wasnt there prior, but you hit the nail on the head with the injections.  

You are da man @Foxandxss
