### ISSUE TITLE
bower referencing angular-toastr.tpls.js in main but dist has only angular-toastr.js in version 1.7.0

### ISSUE THREAD

**Issue by realavaloro** [Foxandxss/angular-toastr#164]
This is somehow related to https://github.com/Foxandxss/angular-toastr/issues/59

I use bower to install `"angular-toastr": "1.7.0"`

I noticed the angular-toastr _bower.json_ main references` "./dist/angular-toastr.tpls.js"` but inside dist folder there is only `angular-toastr.js` and `angular-toastr.css`

I guess this is an inconsistency and I can override the main in my section to reference properly the `"./dist/angular-toastr.js"`, but **where is the ` "./dist/angular-toastr.tpls.js"`**? Does this mean there is no template file anymore?
PS: it's the first time I use angular-toastr so I don't even know what's the templates file for.

**Comment by Foxandxss** [comment]
That is weird my friend, I can see all the files in there:

![](http://puu.sh/ncRFc/a90bf9130a.png)

The template is the toastr template. That .tpls file is the one that has the template integrated (if you don't plan in creating your own).

**Comment by realavaloro** [comment]
my mistake! you're right, my Visual Studio was nesting the tpls under the js and couldn't see it despite show all files in my project explorer. duh!
