### ISSUE TITLE
Is it possible to use a toast inside a defined html placeholder?

### ISSUE THREAD

**Issue by realavaloro** [Foxandxss/angular-toastr#165]
I couldn't find details on whether it's possible to have the toast embedded inside my own html element (a <div/> placeholder) so that it doesn't overlap existing html elements.

That'd be handy for validation errors, for example, where I wouldn't like to have an error overlapping form fields.

Any workaround to achieve this would be great though

**Comment by Foxandxss** [comment]
yeah, you can swap the container with another element so you can insert the toasts inside it. Check the docs for the `target` option.

**Comment by realavaloro** [comment]
Thank you, I managed to overwrite the target but I have the following questions:

- `target` seems to accept an html element such as body, html, div, etc. But what if i'd like to reference a specific element like <div id="errorshere"></div> or even better an element with certain class? I failed attempting that..

- I can configure the toastr container with `angular.config(functionToConfigureToastr)` as per documentation. But could I override the `target` at runtime later in any controller? The toastr seems to accept options but `target` is not one of them.

I ask this because ideally I'd like to have toastr behaving as per default but for some views I'd like to specify its `target` so that it doesn't overlap things.

**Comment by Foxandxss** [comment]
> target seems to accept an html element such as body, html, div, etc. But what if i'd like to reference a specific element like or even better an element with certain class? I failed attempting that..

It should technically work if you pass something like `.foo` to it for a class.

> I can configure the toastr container with angular.config(functionToConfigureToastr) as per documentation. But could I override the target at runtime later in any controller? The toastr seems to accept options but target is not one of them.

inject `toastrConfig` in your controller and modify it there.

**Comment by realavaloro** [comment]
Great! Gracias Jesús
