### ISSUE TITLE
Different templates for different toastr's

### ISSUE THREAD

**Issue by SlippySken** [Foxandxss/angular-toastr#167]
Hello,

is it possible to change the template for every toastr?
I tried something like this:

```
toastr.info("Document ready text", "Document ready header" , {
                'templates': {
                    'toast': 'new-document-toastr.html'
                },
                'extraData': {
                    'userDocument': userDocument
                }
            });
```

I added a template with the 'new-document-toastr.html' to the template cache. Because I want to use the standard toastr for other toastr messages I added the 
`"angular-toastr/dist/angular-toastr.tpls.js"`
file to my index.html

**Comment by Foxandxss** [comment]
It is not possible right now. I had lot of troubles with custom templates due to `replace: true` and I need to rewrite the whole css to fix that. Still will take a peek to see if I can workaround that for that feature.

**Comment by Bogatinovski** [comment]
What is the status with this feature? Is it possible to have multiple different custom templates at the same time now?
