### ISSUE TITLE
Change positionClass for different toasts

### ISSUE THREAD

**Issue by clinton2111** [Foxandxss/angular-toastr#169]
First of all thank you for the awesome library. Really appreciate the trouble take to create something so useful. I just wanted to know i used the following settings to change the position of my toasts

    angular.extend toastrConfig,
		positionClass: 'toast-top-center'
		timeOut: 4000

But this applies for all the toasts throughout my application. Is there a way i could set the `positionClass` to a different position for certain toasts, say like chat messages which i would like to show at the top right portion of my screen rather then in the center?

Thank you for your help in advance

**Comment by Foxandxss** [comment]
There is an explanation on the README (in the FAQ)
