### ISSUE TITLE
Remove previus toast with delay when new toast is added on maxOpened

### ISSUE THREAD

**Issue by napcat** [Foxandxss/angular-toastr#172]
Hello,

When maxOpened is reached the timeOut of the last toast is update with the value of a property holding the delay. An exemple:

    {
            maxOpened: 1, 
            preventDuplicates: false,
            preventOpenDuplicates: true,
            extendedTimeOut: 500,
            maxOpenedTimeOut: 500,
            timeOut: 4000,
    }

    add toastA - 4000ms timeout
    add toastB - 4000ms timeout
    removes toastA - stops current timeOut if > maxOpenedTimeOut , and removes toastA at maxOpenedTimeOut value
    add toastC - 4000ms timeout
    removes toastB - stops current timeOut if > maxOpenedTimeOut , and removes toastB at maxOpenedTimeOut value

Or is there a way to do it without creating a new property?

**Comment by Foxandxss** [comment]
Could I get a reproduction on a plunker please? Would be easier for me to understand.

Thank you!

**Comment by Foxandxss** [comment]
Closing as no repro.
