### ISSUE TITLE
Failed to load template: directives/toast/toast.html (HTTP status: 404 Not Found)

### ISSUE THREAD

**Issue by ivarcegeka** [Foxandxss/angular-toastr#174]
It used to work fine but now I get an error when showing a toast:

Failed to load template: directives/toast/toast.html (HTTP status: 404 Not Found)

I also can't find this file in the bower components folder. I already reinstalled the library with bower, but that didn't make a difference.

**Comment by ivarcegeka** [comment]
Never mind. If I include the tpls.js file it works. I overlooked that part.

**Comment by twizzzlers** [comment]
Thank you sir, your comment worked for me. I was working with rails and it was including automatically, I changed to rails api and a static angular website, now I have to include the tpls.js file manually in the index.html. Again, Thank you! =)
