### ISSUE TITLE
Directives are printed twice when calling toastr 

### ISSUE THREAD

**Issue by joeltello** [Foxandxss/angular-toastr#18]
I have a custom directive which gets printed twice when calling toastr inside my AppCtrl. Comment out this line to confirm (script.js):
```
toastr.info("Test!")
```
http://plnkr.co/edit/0A3U2ptzlFJ712EXNHYU?p=preview

Toastr seems to mess up the compiler.

**Comment by Foxandxss** [comment]
Angular got update a couple of times and this issue wasn't from this library. I hope it got resolved.
