### ISSUE TITLE
The Toastr always shown in Green

### ISSUE THREAD

**Issue by mavillar** [Foxandxss/angular-toastr#180]
Hi,

   The plugin works like a charm but the only issue I have is that the bacñground color of the toaster is always green whatever function used: success, error, warning, .... The icon in the toaster correspond to the function used.

What's missing?

**Comment by Foxandxss** [comment]
That shouldn't happen.

I can't tell you more without a repro.

**Comment by Foxandxss** [comment]
Closing as there is no repro.
