### ISSUE TITLE
Toast overlaps the status bar of iOS7 (or higher)

### ISSUE THREAD

**Issue by xfally** [Foxandxss/angular-toastr#181]
Hi~ I have an *ionic* App which includes angular-toastr (great work!). CSS class `toast-top-full-width` is used but no matter what `target` is assigned, the toast always overlaps the status bar of iOS7 (or higher).

screenshot is as follow

![simulator screen shot 6 jun 2016 5 14 05 pm](https://cloud.githubusercontent.com/assets/5096620/15817839/901a1228-2c0c-11e6-9acf-440c4b5331a5.png)

config codes are

```js
.config(['toastrConfig',
	function(toastrConfig) {
		angular.extend(toastrConfig, {
			extendedTimeOut: 1000,
			timeOut: 2 * 1000,
			tapToDismiss: true,
			newestOnTop: true,
			positionClass: 'toast-top-full-width',
			preventDuplicates: false,
			preventOpenDuplicates: true,
			target: 'body'
		});
	}
])
```

Noticed toast's related CSS codes are

```css
.toast-top-full-width {
  top: 0;
  right: 0;
  width: 100%;
}
```

Should I modify the `top` by hand, or any other better way to custom the position? Many thanks!

**Comment by Foxandxss** [comment]
I am not a CSS guy, but can't you create a selector / media query or something that will only applied to iOS? Perhaps happens on android too.

**Comment by xfally** [comment]
Aha, my App is a HybridApp, so Android device has been tested and work well, because it has the different WebView layout from iOS 7 (or higher).

As ionic framework, WebView is separated from status bar on Android, but on iOS it is allowed to overlap status bar which satisfy the UI design of iOS 7 (or higher).

> More info: https://github.com/apache/cordova-plugin-statusbar

I tried to review your codes, and found something helpful:

```js
    function _createOrGetContainer(options) {
      if(container) { return containerDefer.promise; }

      container = angular.element('<div></div>');
      container.attr('id', options.containerId);
      container.addClass(options.positionClass);
      container.css({'pointer-events': 'auto'});

      var target = angular.element(document.querySelector(options.target));

      if ( ! target || ! target.length) {
        throw 'Target for toasts doesn\'t exist';
      }

      $animate.enter(container, target).then(function() {
        containerDefer.resolve();
      });

      return containerDefer.promise;
    }
```

The generated html codes are:

```html
<body>
<div id="toast-container" class="toast-top-full-width" style="pointer-events: auto;">
<div class="toast toast-info" ng-click="tapToast()" toast="" style="">
  <div ng-switch="" on="allowHtml">
    <!-- ngSwitchDefault:  --><!-- ngIf: title --><!-- end ngSwitchWhen: -->
    <!-- ngSwitchDefault:  --><div ng-switch-default="" class="toast-message" aria-label="Please login">Please login</div><!-- end ngSwitchWhen: -->
    <!-- ngSwitchWhen: true -->
    <!-- ngSwitchWhen: true -->
  </div>
  <!-- ngIf: progressBar -->
</div>
</div>
```

A `<div>` with id `toast-container` (also said by *README.md*) is created and bound to `target` (here is `<body>`). The div also has `positionClass` (here for me is `toast-top-full-width`):

```css
.toast-top-full-width {
  top: 0;
  right: 0;
  width: 100%;
}

#toast-container {
  position: fixed;
  z-index: 999999;
  /*overrides*/
}
```

You can see `#toast-container` has `position: fixed` which works with `.toast-top-full-width`'s `position: fixed`, this means position it at a specified position relative to the screen's viewport! It's OK for web browser, but not so good for iOS device.

More info: https://developer.mozilla.org/en-US/docs/Web/CSS/position

As said before, Android's WebView layout is different from iOS's, so if container uses `position: fixed` and is bound to `<body>`, it works well on Android but not compatible to the overlapped status bar on  iOS 7 (or higher).

For my App, I have two solutions.

- One is to use `position: absolute` which locates div relative to its first parent element (here is `<body>`). I tried

```html
<div id="toast-container" style="position:absolute;top:20px;"></div>
```

but not work, because `_createOrGetContainer` ignores `style` attribute, so can't use `style` to override the default class. *As your project is created for universal AngularJS, so i don't want to modify it directly.*

- Another way is to combine css

```css
.platform-ios.platform-cordova #toast-container .toast {
  margin-top: 20px;
}
```

ionic add class `.platform-ios` and `.platform-cordova` at runtime, which means it's a WebView on real iOS device (ps: another class `.platform-browser` means run in Browser like Chrome, Safari...)

The result is as below

![simulator screen shot 7 jun 2016 11 00 53 am](https://cloud.githubusercontent.com/assets/5096620/15845125/7f0be83a-2ca2-11e6-91fe-5aadd930f2dd.png)

So I think this issue is not your responsibility, and thanks a lot for your work!
