### ISSUE TITLE
Toastr always displays toast in Upper camel case

### ISSUE THREAD

**Issue by gitsubham** [Foxandxss/angular-toastr#183]
Hi, 
I am using angular toastr , below is my global configs for it.
```
angular.extend(toastrConfig, {
			autoDismiss : true,
			containerId : 'toast-container',
			maxOpened : 5,
			newestOnTop : true,
			positionClass : 'toast-top-right',
			preventDuplicates : false,
			preventOpenDuplicates : true,
			target : 'body',
			allowHtml : false,
			closeButton : true,
			closeHtml : '<button>&times;</button>',
			extendedTimeOut : 1000,
			iconClasses : {
				error : 'toast-error',
				info : 'toast-info',
				success : 'toast-success',
				warning : 'toast-warning'
			},
			messageClass : 'toast-message',
			onHidden : null,
			onShown : null,
			onTap : null,
			progressBar : true,
			tapToDismiss : false,
			timeOut : 5000,
			titleClass : 'toast-title',
			toastClass : 'toast'
		});
	}
```

i am facing a problem that whenever i try to create a toast it always shows the message in Upper camel case.  Consider the code below to create the toast -
```
toastr.success('<input type="checkbox" checked> success generating toastr!', 'With HTML', {
			    allowHtml: true
			  });
```

Below is the snapshot of generated toast
![toastr](https://cloud.githubusercontent.com/assets/3896291/16018598/c0724678-31c2-11e6-9113-629ce3f715cd.png)

Please notice below mentioned problems - 
1. Upper camel case message
2. and it should have shown -With HTML- too as part of toast.

I have used the above piece of code from the angular-toasts document itself according to which the toast must appear like this 
![toastr-doc](https://cloud.githubusercontent.com/assets/3896291/16018440/17624fe2-31c2-11e6-8909-9373bf1631ce.PNG)

Please look into the issue.

**Comment by Foxandxss** [comment]
Could you please create a Plunker repro?

**Comment by Foxandxss** [comment]
Doesn't happen for me, tried the same example. I would check that you are not doing that in your codebase :/
