### ISSUE TITLE
unable to see the toast, using Chrome

### ISSUE THREAD

**Issue by jrmcdona** [Foxandxss/angular-toastr#184]
I can see that I have active toasts and the active toasts incremement when I make the call to toastr.succes('test) but I am not able to see a toast yet.

Not seeing any errors in the console either.  Any ideas?

**Comment by jrmcdona** [comment]
I should add, it doesn't matter what browser I use.  The toast does not toast.

**Comment by Foxandxss** [comment]
I cannot know if you don't give me more information.

**Comment by jrmcdona** [comment]
Sorry about that.  So I am running a basic set up so far.   I am using the CDN to get the files and I noticed they are returning 302 responses, I am not sure if that would be an issue. I can browse to them just fine and as mentioned, no errors and I can see I have active toast.
Using these CDN urls:
https://npmcdn.com/angular-toastr/dist/angular-toastr.tpls.js

Do I need to create the toast-container element or is your JavaScript doing that?  I assume that is handled by your code.      I can provide more info if this doesn't get us anywhere.

Here is the config I am testing with.
        angular.extend(toastrConfig, {
                autoDismiss: true,
                containerId: 'toast-container',
                maxOpened: 10,
                newestOnTop: true,
                positionClass: 'toast-top-right',
                preventDuplicates: false,
                preventOpenDuplicates: false,
                target: 'body'
            });

**Comment by jrmcdona** [comment]
I am using Angular 1.3.8, that is the other important item. Thanks!

**Comment by jrmcdona** [comment]
Update:  I changed from using CDN to downloading your Released.zip and hosting the files.  That did not resolve the issue.   I have tried with and without a config.

My web app is an MVC .NET project but uses Anguar SPA as the content with angular routing.   

Thanks!

**Comment by jrmcdona** [comment]
Sorry for all the message man, got it working!    Found some conflicting css from another team member.  Once I commented out that file, things are toasting now!
