### ISSUE TITLE
style error

### ISSUE THREAD

**Issue by axeldiaz** [Foxandxss/angular-toastr#191]
When I Implemented version 2.0.0 the message show with a wrong "z-index" and the message don't show right.

**Comment by Foxandxss** [comment]
Could you please give me a reproduction?

**Comment by axeldiaz** [comment]
In http://testing.vfct.vfct17001.avnam.net/ we using the version "1.7.0" but if we are using "2.0.0" the notification shows worng.

steps to reproduce:
1)enter to site and register with any mail and any password
2)
![image](https://cloud.githubusercontent.com/assets/1671515/17149643/8bb42ffe-5342-11e6-9fb4-4ff654cc4421.png)
3)Enter data 
![image](https://cloud.githubusercontent.com/assets/1671515/17149662/a557bb1a-5342-11e6-879a-a38f4cd57166.png)

4)  When you press "Grabar"  show notification show behind menu. I suppose because style problem.


REMEMBER: to reproduce the error you must change the scripts toastr to version 2.0.0

sorry for my english.

Regards!

**Comment by Foxandxss** [comment]
Dices que la demo está con 1.7.0 o 2.0.0? Yo la demo la veo bien.

**Comment by axeldiaz** [comment]
La Demo está ahora con 1.7.0 y funciona bien . Pero con 2.0.0 funciona mal. Si vos modificas el script del toastr para ponerlo como en la versión 2.0.0 vas a ver que te funciona mal.

**Comment by Foxandxss** [comment]
Agradecería una reproducción en un plunker, es más sencillo que andar hackeando tu página.

**Comment by samypr100** [comment]
+1 Toasts showing behind some elements due to z-index when using bootstrap and fixed navbar. If I change z-index from 1 to something quite higher, the toasts get displayed correctly.

**Comment by Foxandxss** [comment]
Uhm, is weird, I haven't touch anything for z-index, but my CSS sucks.

Can I have a repro @samypr100 ? :)

**Comment by samypr100** [comment]
After an hour and something, found the issue (it might be css nano, I prefer gulp-minify-css to avoid these things)
The min.css version has:
```
#toast-container {
    position: fixed;
    z-index: 1;
}
```
Whereas the .css version it has:
```
#toast-container {
    position: fixed;
    z-index: 999999;
}
```
I was creating the plunker and it was working fine and I'm like WTF until I switched to the min version and saw it happened.

**Comment by Foxandxss** [comment]
I see, love you mate.

Will fix and release.

**Comment by Foxandxss** [comment]
This is fix. Will release a new version soon.

**Comment by 4231** [comment]
i used ng2-boostrap modal and toastr message show behind modal
is that any solution ?
