### ISSUE TITLE
unknown provider $injector/unpr?p0=toastrConfig

### ISSUE THREAD

**Issue by nanivijay** [Foxandxss/angular-toastr#195]
Hi 
I am using angular-toaster in typescript project. I am trying to set toastconfig options but i am getting unknown provider error. I am trying like below. Please help me in resolving this.

module.config(config);
    config.$inject = ["toastrConfig"]
    function config(toastrConfig: any) {
        angular.extend(toastrConfig, {

            newestOnTop: false,

            iconClasses: {
                error: "f-error glyph-incident-triangle",
                info: "f-information glyph-info",
                success: "f-information glyph-info",
                warning: "f-warning glyph-warning",
            },
            toastClass: "m-alert",
            autoDismiss: false,
            tapToDismiss: false,
            messageClass: "c-paragraph",
            closeButton: true,          

    };

**Comment by Foxandxss** [comment]
Are you sure that you are adding the .js files to it?

**Comment by nanivijay** [comment]
yes. i added. the issue is during minification. after i refer the minified file it worked. Thanks
