### ISSUE TITLE
z-index is wrong within angular-toastr.min.css on version 2.0.0 when installed via bower.json

### ISSUE THREAD

**Issue by meinzeugde** [Foxandxss/angular-toastr#197]
When i used your module my toastr was always behind another container, which was placed absolute.
In the end i found out, that there seems to be a mistake within your minified CSS file.
I'm using an Ionic/PhoneGap Project.

In my _angular-toastr.min.css_ i have the following line:
`#toast-container{position:fixed;z-index:1}`

When i look at your repository, i can not find this mistake...
https://github.com/Foxandxss/angular-toastr/blob/master/dist/angular-toastr.min.css
...all seems right here.

To install _angular-toastr_ i have added the following line to my bower.json:
`"angular-toastr": "2.0.0"`

I even double-checked my installation by removing all bower components and reinstalled them.
At the time of installation i had bower version 1.7.2 installed.
An upgrade to the current bower version 1.7.9 had no effect.

**Comment by Foxandxss** [comment]
Yes, known issue and is fixed. I need to make a release but lately I am swamped. Will release this week.

**Comment by meinzeugde** [comment]
Wow thanks for the fast answer...i'll go with the unminified version until the next release
