### ISSUE TITLE
Why did you take dist out of source?

### ISSUE THREAD

**Issue by mgd216** [Foxandxss/angular-toastr#199]
Greetings, using angular-toastr through bower.  You recently took dist out of source, but your bower file points to:

"main": [
    "./dist/angular-toastr.tpls.js",
    "./dist/angular-toastr.css"
  ],

Can you please either correct the bower.json or put /dist back in?  Thanks.

**Comment by KvChaos** [comment]
dist was added to .gitignore, so bower_install now doesn't send down /dist.  Missing something.

**Comment by Foxandxss** [comment]
Ouch! I forgot about bower!

Main reason I took `/dist` out is because people sends PRs and the change `/dist` too and makes the merge of the PR a pain.

Another reason was not really needing it, but I forgot about bower.

That being said, why are you using bower? Bower is "deprecated" and all the new libraries are not supporting bower anymore. I am considering dropping bower support as well.

**Comment by mgd216** [comment]
Thanks for the quick reply, unfortunately our application is using a
template called INSPINA from WrapBootstrap.  The Angular version of that
template uses angular-toastr.

While I agree, would love to move away from bower, we are stuck on this
template for awhile.  If you could reload the /dist directory it would be
greatly appreciated.  Thanks.

**Comment by Foxandxss** [comment]
Done, please tell me if that fixes it for you.

**Comment by mgd216** [comment]
Wow, thanks for the quick help.  I see the dist in github, but there must
be a cached copy somewhere, bower install still pulling without /dist.  No
worries though, with it checked in, should resolve soon.  Again thanks for
the quick response.

**Comment by mgd216** [comment]
And BTW, with your point, we will start looking at trying to move this
template off bower dependency ;)

**Comment by KvChaos** [comment]
Absolutely, thanks Foxandxss!  Appreciate the quick reply on a Sunday!

**Comment by Foxandxss** [comment]
Ill probably need to make a new release, bower is a bit dumb on this. Please try again, say in an hour and I will make a new release if needed.

**Comment by dkenzik** [comment]
+1 - Just noticed this. Glad it's covered.

**Comment by RobEDarling** [comment]
Hey Guys - Just an FYI - tried this via bower now and the release still does not contain dist.

**Comment by Foxandxss** [comment]
Fixed.

**Comment by RobEDarling** [comment]
Thanks!!  Appreciate it!
