### ISSUE TITLE
Add to CDN

### ISSUE THREAD

**Issue by dhoomm** [Foxandxss/angular-toastr#20]
Can you please add this to any CDN such as http://cdnjs.com

**Comment by javorosas** [comment]
+1

**Comment by chaitanyakuber** [comment]
why is 1.0.2 not on a CDN ?
We love this library and really want to use but it needs to be on cdnjs.com or similar

**Comment by Foxandxss** [comment]
@chaitanyakuber I tried, but cdnjs is a 600mb repo with thousand of files. My mac decided to stop working when I decided to "cd" into the directory to put angular-toastr. Their way to add new libraries is the biggest crap ever invented.

**Comment by saaqibz** [comment]
+1

**Comment by kyrylkov** [comment]
+1

**Comment by Foxandxss** [comment]
I will reconsider it when I release 2.0.0

**Comment by svuser1** [comment]
+1

**Comment by ashernevins** [comment]
+1

**Comment by chaitanyakuber** [comment]
@Foxandxss there are plenty of other CDNs around....

**Comment by Foxandxss** [comment]
I guess. I have to research it more, sorry, I have lot of other projects consuming my time.

**Comment by Foxandxss** [comment]
So there is [npmcdn](http://npmcdn.com) which is awesome as a CDN. You can use any npm package as a CDN, so I added instructions on the main page.

Also, check a [plunker here](http://plnkr.co/edit/eibgiKPhIPPURzka3O2T)
