### ISSUE TITLE
Release 2.1.0 missing `dist` folder

### ISSUE THREAD

**Issue by indieforger** [Foxandxss/angular-toastr#200]
Latest release tagged as 2.1.0  comes without `dist` folder if installed with 
```
bower install angular-toastr
```

or 
```
bower install angular-toastr#2.1.0
```

It will be great to get it patched with 2.1.1

**Comment by Foxandxss** [comment]
That was just reported. I forgot about bower. I will release a hotfix later.

But I am not sure if I am going to support bower anymore in the future, there is no reason to :/

**Comment by indieforger** [comment]
Thanks @Foxandxss. Why is there no reason to support bower. Is it because of Webpack, JSPM, Browserify? Could you please point me to the right direction?

**Comment by Foxandxss** [comment]
Bower was useful when there wasn't any other package manager. Yes, we had NPM but it wasn't "ready" for the frontend.

But with new tools like browserify, systemjs, webpack... npm packages started to be more useful so all the frontend ecosystem started to move gradually to NPM.

Nowadays, new packages are not released to bower anymore. NPM works way better in all aspects so there is no reason to keep bower anymore.

**Comment by indieforger** [comment]
Thanks a lot.
