### ISSUE TITLE
Max number of notification

### ISSUE THREAD

**Issue by katmai7** [Foxandxss/angular-toastr#22]
What about add max number of visible notifications?

**Comment by Foxandxss** [comment]
Thinking twice @softengi @katmai7. What would be the idea when the maximum number of toasts is reached? Discard new ones? Remove the last one to put a new one? Queue them?

**Comment by softengi** [comment]
I would suggest closing off the oldest toast and add the new one.

**Comment by Foxandxss** [comment]
This is done on `1.0.0-beta.1`

**Comment by softengi** [comment]
@Foxandxss I see that you added support to queue the new notifications. Could you make it configurable to support closing off the oldest toast, as well. If not, could you suggest how I can achieve the same, at my end?

**Comment by Foxandxss** [comment]
@softengi I am afraid that it doesn't support that. I tried, I really tried but I never get it right. Seems to be easy but there is always a race conditition of creating vs destroying and I couldn't get it right.

If you or anyone else wants to try it, send a PR.
