### ISSUE TITLE
Discussion about allowing HTML

### ISSUE THREAD

**Issue by Foxandxss** [Foxandxss/angular-toastr#3]
I want to discuss here of what should we do about trusting html.

I saw various ways, and I am not sure of any of them:

As today, you can add html onto it, `$sce` will trust your html but I am unsure how it works vs `XSS`. Using `ngSanitize` is also an option, but it doesn't allow to use form items on the toast.

The problem with `$sce` is that you can't put directives into the trusted HTML (that is intended). That doesn't mean I can create a directive where you can put any kind of html on your toast (even forms that will work with your scope), but that is highly insecure.

I want to discuss what are your thoughts about this.

**Comment by brutalcrozt** [comment]
i got $sce warning with 

0.  `AngularJS v1.5.7`
0.  `toastr 2.1.1` (not validate)

my intention enabling html just using <br>
it work on http success callback with `toastr.success`

and it's throw $sce error when on fail callback, even with no html
