### ISSUE TITLE
onShown and onHidden not working properly

### ISSUE THREAD

**Issue by edwincen** [Foxandxss/angular-toastr#33]

**Comment by Foxandxss** [comment]
Care to give more information? Are you using the latest version from master? I haven't push to bower yet

**Comment by edwincen** [comment]
Oh, ok, updated to latest version, and it's working just fine.
However, seems maxOpened will cause 'prepend of undefined' error

**Comment by Foxandxss** [comment]
I need to be able to reproduce that.

**Comment by edwincen** [comment]
I think it's easy to reproduce, just add maxOpened : 1 into options

**Comment by Foxandxss** [comment]
Oh, I see, I can reproduce it.

**Comment by Foxandxss** [comment]
Let's continue in #34
