### ISSUE TITLE
Possible issue with maxOpened

### ISSUE THREAD

**Issue by Foxandxss** [Foxandxss/angular-toastr#34]
If the toasts are opened THAT fast, the restriction is no longer respected and toasts gets sticked.

Need to research about that.

**Comment by Foxandxss** [comment]
I try to remove the first shown item before I show a new one.

So far so good, but if you try to show toasts really quick, it will try the removal too many times and will end ignoring the `maxOpened` and leaving some orphan toasts that won't go away.

I am trying to fix it somehow but so far I am stuck.

If anyone wants to make a try, please I am open to ideas.

**Comment by schranerd** [comment]
I still see this issue and can reproduce it in the demo here

https://foxandxss.github.io/angular-toastr/

when I change the code slightly to

` $scope.openToast = function() {
        for (i=0; i<3; i++) {
      openedToasts.push(toastr[$scope.options.type]($scope.toast.message, $scope.toast.title + new Date()));
        }
    };
`
and then select the options as shown on the screenshot below
- maxOpened to 2
- autoDismiss to true (the issue does not occur if this on is set to false

Note that 3 toasts are shown which is beyond the maxOpened
![screen shot 2016-09-12 at 13 48 04](https://cloud.githubusercontent.com/assets/13308782/18466357/956c5acc-79c5-11e6-8b92-02011f7e0d15.png)
