### ISSUE TITLE
Fast dismissing of toasts results in preserving them

### ISSUE THREAD

**Issue by nikolavp** [Foxandxss/angular-toastr#36]
If I create multiple toasts(really fast) and then try to dismiss them fast(by clicking on them) at some point one of the toasts is not removed and it is not dismissed after the timeout. I know that this is sort of spamy but it is annoying(I have to refresh the page to remove the toast)

Note that this happens with dismiss on click and a dedicated close button(not sure if this is relevant)

**Comment by Foxandxss** [comment]
What version and... are you using `maxOpened` ?

**Comment by nikolavp** [comment]
I am using the demo from here http://foxandxss.github.io/angular-toastr/ . I was able to reproduce it both in chrome and firefox. maxOpened didn't matter at unless it is 1 in which case this cannot be reproduced. Just try to spam it a little more. Tell me if you need a recording or something

**Comment by Foxandxss** [comment]
Yeah, wasn't that hard to notice. Will look for a fix :)

**Comment by Foxandxss** [comment]
Care to try again on the demo? I think I fixed it.

**Comment by nikolavp** [comment]
Yes, this fixed it for me :+1:
