### ISSUE TITLE
For supporting 1.2.28,you have to change some code.

### ISSUE THREAD

**Issue by myhirra** [Foxandxss/angular-toastr#38]
## As Angular below version 1.3 doesn't support `Promise`

When I use Toastr in my Angular project whose angular version is 1.2.28 , I have to change some codes. I display some of them, it may help.

### at line 59
```javascript
   $animate.leave(toast.el, function() {
          if (toast.scope.options.onHidden) {
            toast.scope.options.onHidden(wasClicked);
          }
         ....
```

### at line 124

```javascript
$animate.enter(container, body, '', function() {
        containerDefer.resolve();
      });
```

### at line 145
```javascript
if (options.newestOnTop) {
            $animate.enter(newToast.el, container, '', function() {
              newToast.scope.init();
            });
          } else {
            $animate.enter(newToast.el, container, container[0].lastChild,function() {
              newToast.scope.init();
            });
          }

```

**Comment by myhirra** [comment]
format content.

**Comment by Foxandxss** [comment]
Hello, The last supported version for 1.2.x is the version 0.4.x. Since that I don't support it anymore because there are some breaking changes.

Since there is no reason to stay on 1.2.x (1.3.x doesn't have any big BC) I don't feel like I want to support two codebases at the same time.
