### ISSUE TITLE
Which version to use for angular 1.2.*?

### ISSUE THREAD

**Issue by ElectricMaxxx** [Foxandxss/angular-toastr#39]
Hi,
tried to work with this module, but it does not work with angular 1.2.* as $animate.enter() returns no promise before 1.3. angular-toastr is using that promise which causes issues in my application. 
So is there a version of angular-toastr which i can use with angular version < 1.3 ?

**Comment by Foxandxss** [comment]
There is a note in the readme, on the very top.

**Comment by ElectricMaxxx** [comment]
ohhh sorry :-)
