### ISSUE TITLE
Disable toastr extendedTimeOut option

### ISSUE THREAD

**Issue by mehmedju** [Foxandxss/angular-toastr#41]
Hi,
is there any way to disable a toaster option extendedTimeOut how the notifications would not disappear when is mouse hovered over it.
It's not the solution assign some value to this option like 50000. I would appreciate more smoother way to set this.
Thanks!

**Comment by Foxandxss** [comment]
Sorry, I don't think I follow your issue. You want to not close a popup even if you hover over it?

**Comment by mehmedju** [comment]
Exactly that!

On Tue, Feb 10, 2015 at 11:47 AM, Jesús Rodríguez Rodríguez <
notifications@github.com> wrote:

> Sorry, I don't think I follow your issue. You want to not close a popup
> even if you hover over it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Foxandxss/angular-toastr/issues/41#issuecomment-73679704>
> .
>



-- 

Mehmed Jusić

Software Engineer  Product Development

*Maestral*Solutions | Sarajevo

Founding Member of HUB387

Milana Preloga 12/3

71000 Sarajevo



web: maestralsolutions.com | twitter: *@maestralsol
<http://twitter.com/maestralsol>* | linkedin: maestralsolutions
<https://www.linkedin.com/company/maestral-solutions-llc>

**Comment by Foxandxss** [comment]
I don't support that right now because I wanted to match the original one. It is not a hard option to add, but that option wouldn't end on the old version you're using for angular 1.2.x

**Comment by Foxandxss** [comment]
The only real way to disable it is also putting timeout to 0 so the only way to remove a toast is by clicking it.

**Comment by squadwuschel** [comment]
hi, I have the same problem it would be nice if I could tell a toastr to stay open until I close it. Like a third Parameter because we need that the errors stay open until I close them by hand.

toastr.info('We are opened today from 10 to 22', 'Information', true);

OR

toastr.info('We are opened today from 10 to 22', true);

that would be really nice

**Comment by Foxandxss** [comment]
@squadwuschel In that case, you can do:

```javascript
toastr.info('We are opened today from 10 to 22', 'Information', {
  timeOut: 0,
  extendedTimeOut: 0
});
```

That will make the popup stick until you click them.

**Comment by squadwuschel** [comment]
oh cool thats fine thx :-)

**Comment by Akbarics** [comment]
Prevent close Toastr on Click by this code:
$.fn.noop = function () { return this; };
toastr.options.hideMethod = 'noop';

**Comment by Nils-hysteria** [comment]
> Prevent close Toastr on Click by this code: $.fn.noop = function () { return this; }; toastr.options.hideMethod = 'noop';





https://lyndonnobility.github.io/23Hbt2vFBmaDsHxrUcD1BUTtBrjS0oxipxtyzwUHuXWZj1S9m0I9noVW/
