### ISSUE TITLE
bower install does't download angular-toastr.tpls.js and angular-toastr.tpls.min.js

### ISSUE THREAD

**Issue by zahidmak** [Foxandxss/angular-toastr#43]
Really great work. but one issue as mentioned above. If you could resolve this it would be great.
Thanks

**Comment by mattblang** [comment]
It does download them, but the `main` attribute in bower is set to use `angular-toastr.js` rather than `angular-toastr.tpls.js`, which causes an issue if you are relying on `main` for grunt or gulp.

**Comment by Foxandxss** [comment]
@mattblang no. In the past there was only `angular-toastr` and not `angular-toastr.tpls.js` and I forgot to change that on bower.

Since I am not a fan of bower, what should I put? Both files or just the tpls one?

**Comment by Foxandxss** [comment]
I set tpls to be the one installed. Will be on beta.3 which I will release today and if everything goes well for a week, I will release the final version.

**Comment by zahidmak** [comment]
Thanks @Foxandxss  for quick response on my email. beta 3 has tpls file. It would be great if you release the final version.

**Comment by Foxandxss** [comment]
@zahidmak you can `bower install angular-toastr#1.0.0-beta.3` for now.
