### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by MichMich** [Foxandxss/angular-toastr#45]
Compliments for the nice and simple plugin! 
The only thing missing is the Progress Bar ... wil this be included in a future version?

**Comment by Foxandxss** [comment]
Oh, I wasn't aware of the progress bar addition, I will take a look after I release 1.0.

**Comment by MichMich** [comment]
Great! Thanks! :)

**Comment by ArtworkAD** [comment]
@MichMich @Foxandxss I think this does not belong inside toastr. You have to keep things clean and easy.

**Comment by Foxandxss** [comment]
@ArtworkAD yeah, but the original implementation (where this library started off) has that progress bar and it doesn't seem to be really intrusive. That is why I am considering it.

**Comment by olso** [comment]
Any updates?

**Comment by Foxandxss** [comment]
not really, I have lot of more stuff to do ;(

**Comment by Foxandxss** [comment]
Progress bar support in master! I will release later today or tomorrow :)

**Comment by olso** [comment]
:+1:
