### ISSUE TITLE
"main" field in package.json should not be an array.

### ISSUE THREAD

**Issue by chengyuhui** [Foxandxss/angular-toastr#47]
According to [documention](https://docs.npmjs.com/files/package.json#main), the "main" field should not be an array, or it'll break browserify.

**Comment by Foxandxss** [comment]
I see, should I ignore the .css then and just include the tpls.js ?

**Comment by chengyuhui** [comment]
That's right. Thanks.

**Comment by Foxandxss** [comment]
Will change it, but I guess I would need to release a hotfix version, right?

**Comment by chengyuhui** [comment]
Yes.
Now I have to manually change package.json or browserify will crash.

**Comment by Foxandxss** [comment]
That should be it. Thanks for the heads up.
