### ISSUE TITLE
How to dismiss a sticky toast

### ISSUE THREAD

**Issue by fortesl** [Foxandxss/angular-toastr#49]
If a sticky toast is created like this:

toastr.success('I am sticky', 'Title', { timeOut: 0, extendedTimeOut: 0 });

How do I then dismiss it? Is there a command for closing a toast?

Thank you

**Comment by fortesl** [comment]
I am using the version for angular 1.2.x. I need to leave the toast on the screen until the application state changes and close the toast without user action.

**Comment by Foxandxss** [comment]
You should be able to dismiss them using a click.

**Comment by fortesl** [comment]
No, I cannot use a click it has to go away without user action. I found the answer in the demo app.js code but not in the readme. The commands I needed were toastr.clear() and toastr.clear(toast).

Awesome toasts to you.
Thank you.

**Comment by vishnur-github** [comment]
Have you found any solution for this ?
