### ISSUE TITLE
Toastr container is not a jqLite object

### ISSUE THREAD

**Issue by luckycadow** [Foxandxss/angular-toastr#52]
In _createOrGetContainer() the target container for toastr is found using document.querySelector() and is passed into $animate.enter().  This throws an exception as $animate.enter() is expecting a jqLite object.

**Comment by Foxandxss** [comment]
Uhmmm, that is not good at all. Will check it and report / fix.

**Comment by Foxandxss** [comment]
Could you tell me more? Browser, code, something.

**Comment by luckycadow** [comment]
I'm using latest Chrome.  I just created a merge request if you'd like to review it.
