### ISSUE TITLE
onShown, onHidden never fire

### ISSUE THREAD

**Issue by n8m** [Foxandxss/angular-toastr#55]
toastr.warning('something', null, {onShown: function(){
  console.log('something');
})

Console.log will never be displayed. I'm using latest version via bower. Do anybody have this issue?

**Comment by Foxandxss** [comment]
What version of `angular-toastr` ?

**Comment by Foxandxss** [comment]
If you remove the null parameter, I mean, using it like:

```javascript
toastr.warning('something', { 
  onShown: function() {
    console.log('something');
  }
}
```

It works. Still the null shouldn't interfere with it, I will leave this open and fix it on my next iteration.

**Comment by n8m** [comment]
Great. Thanks. It works.

**Comment by mrchacon** [comment]
The current toastr can be passed as parameter on the callback function? Is there a way to handle the current toastr shown or hidden?

Thanks

**Comment by Foxandxss** [comment]
I don't think I can follow what you are asking.

**Comment by mrchacon** [comment]
e.g. onShown property be like:

function(_toastr) {
    console.log(_toastr);
}

Where _toaster is the latest toastr obj shown

**Comment by Foxandxss** [comment]
You can access the toastr from inside the callbacks, there is no need for a parameter.
