### ISSUE TITLE
Dismiss programatically

### ISSUE THREAD

**Issue by red010182** [Foxandxss/angular-toastr#56]
I want to use this toast to show loading indicator (especially in http request). However, I would never know how long a http request would take so I cannot use timeout parameter to control the toast. I want to fire a loading toast before http request and close it in response callback without a user interaction. 

Any way to do that?

**Comment by Foxandxss** [comment]
Sure, you can do something like (writing from memory):

```javascript
var toast = toastr.info('Loading stuff', {
  timeOut: 0,
  extendedTimeOut: 0
});
$http.get('/my/endpoint').then(function(result) {
  toastr.clear(toast);
  return result;
});
```

Basically, you fire a permanent toast and then when your `$http` request resolves, you close the toast. It is really important that you return result from it, so when you chain the promise in your controller, it will receive those results.

**Comment by red010182** [comment]
Thank you, works perfect.
