### ISSUE TITLE
Add possibility of translation via http://angular-translate.github.io/

### ISSUE THREAD

**Issue by ArtworkAD** [Foxandxss/angular-toastr#57]
You call toasts from within controllers, but this has a major downside: you have to hardcode the text for the toasts. If you provide a template that uses http://angular-translate.github.io/ a toast call would look like this:

    toastr.info('SAVED_KEY');

in template:

    {{ MSG | translate }}

and the angular translate module would determine the message for SAVED_KEY which is "Saved!".

**Comment by ArtworkAD** [comment]
Could be related https://github.com/Foxandxss/angular-toastr/issues/3

**Comment by Foxandxss** [comment]
i18n is always good, but I don't really want to make toasts insecure.

**Comment by dyanarose** [comment]
@ArtworkAD would it be possible for you to inject the translation service or the resolved translations instead?

so instead of:
`toastr.info('SAVED_KEY');`

you have something like:
````
$translate('SAVED_KEY')
.then(function(translation)
{
    toastr.info(translation);
});
````

**Comment by PerchHero20** [comment]
Hello, I am stuck any advices?
In my en.json I got
"Index_Language_English": "English",
I can call it from html with {{ 'Index_Language_English' | translate }}
In js I have
toastr.warning("English");
I want to add translations so as the English word to be translated.
can you provide any advice?

**Comment by Foxandxss** [comment]
I am closing this because it is a concrete use case I cannot merge on the library. If you want to use the filters for i18n, you can override the template (Use the version without tpls and create your own template, check the readme).

**Comment by mmichaelbiz** [comment]
Will go with a custom template, however would be great to re-visit this and add it as part of the functionality. 

Essential for multi language apps and hard coding the messages is not great even for single language apps. This could be a simple and extendable way to manage messages in one place.

How about adding the ability to add a 'translate' config and let toastr know to use the translate filter? Those who have security concerns can leave it off and those who need it can enable at their own risk.

:+1:

**Comment by Foxandxss** [comment]
It is still better to create another template for it. If I start adding opinions to the template, it will be a monster.

On the other hand, that library for i18n is not the only one and even applying filters is not the only option for that concrete library.

**Comment by mmichaelbiz** [comment]
No worries. Took about 5 mins to set up the template and its working like a charm!
