### ISSUE TITLE
Add support for toastr option "preventDuplicates"

### ISSUE THREAD

**Issue by fbliss** [Foxandxss/angular-toastr#58]
preventDuplicates = true|false

I'm using toastr in conjunction with a hotkey tool, so messages quickly stack up if you lay on your 'ctrl+s' for longer than you should :D

**Comment by Foxandxss** [comment]
Ya, sure, that is easy to implement. Will do it hopefully this weekend on my "toastr" time.

**Comment by fbliss** [comment]
Thanks!  No worries.  I was poking around but didn't have time to do it ultimately.

**Comment by Foxandxss** [comment]
This is now in master.
