### ISSUE TITLE
show/hideEasing not working

### ISSUE THREAD

**Issue by mrchacon** [Foxandxss/angular-toastr#62]
The toastr message appears but without an animation. This properties can be handle from .config? 

My version of angular is 1.3.2 with it's respective ngAnimate.

**Comment by Foxandxss** [comment]
Do you have the latest angular-toastr and also `ngAnimate` imported as a dependency on your module?

**Comment by mrchacon** [comment]
Sure, I have the latest release of angular-toastr imported also with the ngAnimate version 1.3.2. Animations work right with this version?

Thanks

**Comment by Foxandxss** [comment]
yes, it should work, can you gist some code?

**Comment by mrchacon** [comment]
Here's my app dependencies 

https://gist.github.com/mrchacon/12a13d55f81b5cce3dbb#file-gistfile1-txt

**Comment by Foxandxss** [comment]
There is no need to override all the options, just the ones you want to change. Still, that shouldn't cause your "non" animations.

**Comment by Foxandxss** [comment]
Please, reopen if you have a plunker or something, but I can't reproduce it.
