### ISSUE TITLE
Add less files to bower

### ISSUE THREAD

**Issue by piernik** [Foxandxss/angular-toastr#63]
Can You add less files to bower? I could use it to change colors

**Comment by Foxandxss** [comment]
Damn, I understood that there is too much files and you wanted less, not `less` file. Having the css is not enough?

**Comment by piernik** [comment]
using `less` is much better ;)

**Comment by Foxandxss** [comment]
I still don't think this is a good idea, bower packages should avoid sources. You can still modify the final css.

**Comment by piernik** [comment]
Do as You will.
I often use less file to compile css, but yes, I can manually download Your less files (and I did ;) )
