### ISSUE TITLE
Add the template path to the toastrConfig constant

### ISSUE THREAD

**Issue by robertsoniv** [Foxandxss/angular-toastr#64]
It would be really nice if the template path were configurable rather than hard coded. I use an html2js build process that puts templates in the $templateCache based on directory structure. While using .run to add my custom template to the hard coded location works; I'd like my "alerts" module directory to have an alerts.tpl.html file that gets swallowed up by my build process and then is recognizable by angular-toastr through something like this
```
angular.extend(toastrConfig, { templatePath:'alerts/alerts.tpl.html'})
```

**Comment by Foxandxss** [comment]
Sounds reasonable to me.

**Comment by intellix** [comment]
+1 for this. I'm copying all templates from the "template" directory, which is used all across ui-bootstrap etc. This one uses "templates" so now have 2 folders :D Generally I wish it was easier in Angular to override templates

**Comment by Foxandxss** [comment]
Not as a solution for this issue (I will properly fix it with the option when I get a day to invert on this library) but you can always use `$templateCache` to put all your templates and as a key, the route that the directives is looking for the template.

**Comment by Foxandxss** [comment]
That is done, will release soon.
