### ISSUE TITLE
Remove replace from directives

### ISSUE THREAD

**Issue by Foxandxss** [Foxandxss/angular-toastr#65]
Dummy issue so I don't forget about it.

**Comment by Foxandxss** [comment]
I would love a PR for this, it is CSS related mostly and meh, I suck at it. Maybe I can workaround it via code as well...

**Comment by jjalonso** [comment]
Dont be lazy fox!

**Comment by Foxandxss** [comment]
I am planing this for 2.0.0 where I plan to rewrite the CSS to support this.
