### ISSUE TITLE
createTostEl does not always compile the toast directive

### ISSUE THREAD

**Issue by JohannesRudolph** [Foxandxss/angular-toastr#69]
I am debugging a weird issue right now that I can't unfortunately reproduce in a plunkr - but I see it consistently in the chrome debugger. The issue is that ng-animate does not animate any toasts that are added after the first visible toast. 

I'm using angularjs 1.3.7 if that helps. So I put a debug statement in angular-animate.js to see what's being animated: 

```
      function performAnimation(animationEvent, className, element, parentElement, afterElement, domOperation, options, doneCallback) {
          console.log("performing animation: " + animationEvent + " with class: " + className + " on element " + element[0].outerHTML);
          var noopCancel = noop;

```

Then the output (truncated for relevant lines) for the first toast is: 
```angular-animate.js:1282 performing animation: enter with class: ng-enter on element <div class="toast toast-warning" ng-click="tapToast()" toast="">```

but for the second toast it's:
``` 
angular-animate.js:1282 performing animation: enter with class: ng-enter on element <div toast="" class="ng-scope"></div>
```
    
So it appears to me that the point at which toastr calls $animate.enter the directive is not always expanded/compiled (even though I see the compile call earlier). I'm not sure where the problem is, but someone who knows better about $compile might be able to figure it out. Look for createToastEl and _notify functions in toastr.js

Hope we can solve this in a "code-review" style without a working repro?

**Comment by Foxandxss** [comment]
Without a reproduction is going to be really hard. It could be an issue in your app and we could spend hours and hours in plunker without getting anything.

So I am afraid that we are pretty stuck down here ;(

**Comment by JohannesRudolph** [comment]
I understand. I thought maybe looking at the code something obvious would
spring to mind why the toast directive wouldn't be fully compiled at the
time the promise is resolved and toastr calls $animate.enter on it....

**Comment by Foxandxss** [comment]
ngAnimate is a real pain sometimes to be honest, it could potentially break it indeed. Will take a peek tho.

**Comment by JohannesRudolph** [comment]
@Foxandxss I do have a repro that's easy to do. Go to http://foxandxss.github.io/angular-toastr/ and open the chrome debugger, changing lines 151 in toastr.js to add a console.log statement:

```
      newToast.open.promise.then(function() {
        _createOrGetContainer(options).then(function() {

         console.log("adding toatst: " + newToast.el[0].outerHTML);
```

Now, when you open multiple toasts, you will see that only the first toast added will have a proper outerHTML with an expanded toast directive while subsequent ones do not: 

```
adding toatst: <div class="toast toast-success" ng-click="tapToast()" toast="">
  <div ng-switch="" on="allowHtml">
    <!-- ngSwitchDefault:  --><!-- ngIf: title --><!-- end ngSwitchWhen: -->
    <!-- ngSwitchDefault:  --><div ng-switch-default="" class="toast-message"></div><!-- end ngSwitchWhen: -->
    <!-- ngSwitchWhen: true -->
    <!-- ngSwitchWhen: true -->
  </div>
  <!-- ngIf: progressBar -->
</div>
3VM66 toastr.js:154 adding toatst: <div toast="" class="ng-scope"></div>
```

I'm not sure why compile doesnt do it's job, at least not in the same digest cycle or so it appears.

**Comment by JohannesRudolph** [comment]
This appears to be a digest cycle issue or something. When I pack the thing into a setTimeout it appears to work correctly (but the first toast doesn't show until I add a second one?! it appears there's some special behavior for the first toast). 

            setTimeout(function () {
                _createOrGetContainer(options).then(function () {

                    console.log("adding toatst: " + newToast.el[0].outerHTML);
                    if (options.newestOnTop) {
                        $animate.enter(newToast.el, container).then(function () {
                            newToast.scope.init();
                        });
                    } else {
                        $animate.enter(newToast.el, container, container[0].lastChild).then(function () {
                            newToast.scope.init();
                        });
                    }
                });
            }, 100);

**Comment by Foxandxss** [comment]
I can see that, will take a look.

**Comment by Foxandxss** [comment]
The outerHTML issue is nothing more than a race issue. The log is printed out before $compile finishes with the toast. If you wrap that log (just the log) inside a setTimeout, you will see it correctly.

**Comment by JohannesRudolph** [comment]
Yes, but that same race condition sometimes seems to affect the ability of
ng-animate to animate the enter transition (so we would need to ensure that
animate.enter is called only after compile has finished).

Why does compile not finish synchronously by the way? Seems unintuitive to
me, but I'm not all too deep into angular internals.

**Comment by Foxandxss** [comment]
I don't know, I can't replicate your animation issues, so I can't point to where the issue is ;(

**Comment by JohannesRudolph** [comment]
I can replicate them with my own codebase so far only. When I step through
the code with the debugger I can see that the element passed into
ng-animate ("<div toast") hasn't finished compiling yet, so ng-animate
isn't able to attach the .ng-enter classes to the correct elements. Do you
understand that?

Given the nature of the problem (race condition) it makes sense that we can
only repro the issue in some cases and not in others. In any case,
angular-toastr would need to handle it correctly because it is a bug that
could lead to other issues just as well.

**Comment by Foxandxss** [comment]
Still, I need to be able to reproduce it so I can't create a test for it and fix the issue.

**Comment by Foxandxss** [comment]
The race condition is not necessarily the issue in here. It is just the log gets faster than the rest. Angular will eventually show the toast in the next tick.

**Comment by JohannesRudolph** [comment]
I get the part about reproducing, but I'm not able to sink in the hours to get a repro up right now. All I can tell you is that wrapping animate.enter in a $timeout fixes the animation issue for me, which is not suprising given the race condition nature of the problem. 

The timeout ensures that the directive is fully compiled (i.e. newToast.el.outerHTML has had the 'toast' directive expanded) at the time $animate.enter is invoked on it. To me it's rather suprising that the current toastr implementation works at all - lucky coincidence I guess. The race condition _is there_ and should be fixed, but of course I can understand you'd need a reliable repro first. I'll leave it at that and provide my "hack" below for anyone else stumbling across this issue. 

            $injector.get('$timeout')(function() {
                newToast.open.promise.then(function() {
                    _createOrGetContainer(options).then(function() {
                        if (options.newestOnTop) {
                            $animate.enter(newToast.el, container).then(function() {
                                newToast.scope.init();
                            });
                        } else {
                            $animate.enter(newToast.el, container, container[0].lastChild).then(function() {
                                newToast.scope.init();
                            });
                        }
                    });
                });

**Comment by Foxandxss** [comment]
Thank you.
