### ISSUE TITLE
How to add button click + event on a toater?

### ISSUE THREAD

**Issue by liadlivnat** [Foxandxss/angular-toastr#74]
i'm trying to do the following:

```
toastr.warning("message message. <input class='undo-button' type='text' value='Undo' data-ng-click='callback()' />",
                {
                    callback: function()
                    {
                        console.log("here");
                     
                    }
                });
```
It's not working, any suggestion how to add a callback function from a toaster?

**Comment by Foxandxss** [comment]
Check the README. You can add the `onHidden` callback so when it gets closed, it gets called. You can also check in there if it was closed by itself or via click.

You can't add directives into the message, that is pretty dangerous so I don't allow that.

**Comment by liadlivnat** [comment]
This is not the case since onHidden will call a function once the message will be close and,
i want to add my own callback when somone click on button inside the toastr

i added a button inside the template
```
<input class='undo-button' type='text' value='Undo' data-ng-click='callback()'
```

**Comment by Foxandxss** [comment]
You can't do that with this library. Supporting directives inside the toasts is highly insecure and can open a door for injections.

I had to decide to not allow that. Sorry.

**Comment by SaiPhaniKnappily** [comment]
@Foxandxss I am wondering are you allowing anchorScroll in toastr?
