### ISSUE TITLE
Know when a toast is displaying

### ISSUE THREAD

**Issue by samy100** [Foxandxss/angular-toastr#75]
I know there's preventDuplicates on toastrConfig, but it would be interesting to do other stuff programmatically whether or not a toast is currently showing. Maybe there's already a way to do this and I didn't read correctly but I would like to propose toastr.isShowing() or some kind of variable that we would easily use to figure out if a toast (or multiple) is (are) being displayed at a given time. I basically want to do some other dynamic actions during the toast display transition.

**Comment by Foxandxss** [comment]
There is no official way to do that. Although, I will think about adding some easy way for that.

As today, you could set a flag to true and then set it to false on the `onHidden` callback.

**Comment by samy100** [comment]
I will do this "**set a flag to true and then set it to false on the onHidden callback**" for now, thanks!

**Comment by Foxandxss** [comment]
I added that feature brother.

**Comment by samy100** [comment]
Already using it :+1: :+1: Thanks :100:
