### ISSUE TITLE
Auto-dismiss when limit is set

### ISSUE THREAD

**Issue by tlvince** [Foxandxss/angular-toastr#76]
Given:

```js
angular.extend(toastrConfig, {
  maxOpened: 1
});
```

… I would expect the newest toast to be shown regardless of timeout. Put another way, after opening a toast, subsequent toasts should auto-dismiss the last toast.

**Comment by Foxandxss** [comment]
I hear you. Both behaviors (the current one and the one you say) are good ways to tackle `maxOpened`. Depend on the use case. Some use case would like to close the oldest and then show a new one and other use cases would like to queue them.

To be hones with you, I tried what you expect but I never got it working. If you think you can tackle it, please open a PR, in the meantime, that feature is not supported.
