### ISSUE TITLE
CSS breaks when using grunt build (yeoman.io)

### ISSUE THREAD

**Issue by sclearion** [Foxandxss/angular-toastr#77]
When I compile my angular app the css gets lost. The toast message appears, however lacks css

**Comment by Foxandxss** [comment]
Check that your yeoman grunt/gulp is getting angular-toastr's css as well into the build.

**Comment by sclearion** [comment]
Yes its all there but I think that grunt is mangling the css files. Will look for other alternatives. Thanks

**Comment by Foxandxss** [comment]
That shouldn't be an issue I believe. Ping me back if you find that any of those options is breaking it.

**Comment by sclearion** [comment]
Ok I fixed it: I removed the css declaration from the '' block to a '' and it works now. My mistake. thanks for the quick reply
