### ISSUE TITLE
PositionClass option not being honored

### ISSUE THREAD

**Issue by bubbleheadinc** [Foxandxss/angular-toastr#78]
Looks like the positionClass option isn't being honored. I'm trying to set the positionClass to `toast-bottom-right` but it still uses the `toast-top-right` default class.

```
toastr.success('Hello world!', 'Toastr fun!', {
  timeOut: 0,
  positionClass: 'toast-bottom-right'
});
```
Here is a plunkr with the issue:
http://plnkr.co/edit/VTNYRhRXnSgpfbH3PStC?p=preview

**Comment by Foxandxss** [comment]
See #73 and #67
