### ISSUE TITLE
I'm not able to clone from npmjs using composer and composer-asset-plugin

### ISSUE THREAD

**Issue by alexandernst** [Foxandxss/angular-toastr#84]
Whenever I try to download this repo using composer and [composer-asset-plugin](https://github.com/francoispluchino/composer-asset-plugin) I end up getting this error:

    [RuntimeException]                                                                                                                                                             
    Failed to execute git clone --mirror 'git+https://github.com/Foxandxss/angular-toastr.git' '/home/alexandernst/.composer/cache/vcs/git-https---github.com-Foxandxss-angular-toastr.git/'                                                                                                                                                                    
    Cloning into bare repository '/home/alexandernst/.composer/cache/vcs/git-https---github.com-Foxandxss-angular-toastr.git'...                                                   
    fatal: Unable to find remote helper for 'git+https'

I'm not sure if this is a bug in composer, in the composer asset plugin or in this repo.

**Comment by Foxandxss** [comment]
I asked a friend who uses composer to test it out, I have no idea.

**Comment by alexandernst** [comment]
Got it! It turns out I was using the assets plugin in a wrong way. Check [this](http://stackoverflow.com/questions/30128665/unable-to-find-remote-helper-for-githttps/30195382#30195382)
