### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by joshribakoff** [Foxandxss/angular-toastr#85]
I followed the readme & installed w/ bower. I see these files:
```
 ll bower_components/angular-toastr/**
-rw-rw-r-- 1 josh josh  538 Apr 27 10:18 bower_components/angular-toastr/bower.json
-rw-rw-r-- 1 josh josh 2346 Apr 27 10:18 bower_components/angular-toastr/gulpfile.js
-rw-rw-r-- 1 josh josh 9063 Apr 27 10:18 bower_components/angular-toastr/README.md

bower_components/angular-toastr/dist:
total 64
-rw-rw-r-- 1 josh josh  7200 Apr 27 10:18 angular-toastr.css
-rw-rw-r-- 1 josh josh 12342 Apr 27 10:18 angular-toastr.js
-rw-rw-r-- 1 josh josh  6158 Apr 27 10:18 angular-toastr.min.css
-rw-rw-r-- 1 josh josh  5752 Apr 27 10:18 angular-toastr.min.js
-rw-rw-r-- 1 josh josh 13113 Apr 27 10:18 angular-toastr.tpls.js
-rw-rw-r-- 1 josh josh  6449 Apr 27 10:18 angular-toastr.tpls.min.js

```

When I try to use the plugin, I see these errors to console & I get no toast messages:

![selection_490](https://cloud.githubusercontent.com/assets/4021306/7557697/fc70a560-f74a-11e4-9e80-bd579fde6c6b.png)

I see there's an option to override the template's path. However that template is not present in the distribution. There also appears to be some other issues that I'm not sure how to debug, with the undefined method.

**Comment by Foxandxss** [comment]
You need to use the .tpls version and not the other. That one includes the
template in it.
