### ISSUE TITLE
Always set a valid version for bower dependencies

### ISSUE THREAD

**Issue by ricardobarone** [Foxandxss/angular-toastr#88]
Resolving `latest` is not always safe as it can pick a beta version. It also breaks automatic deployers, such as [Bower Webjars](http://www.webjars.org/bower).

**Comment by Foxandxss** [comment]
Will fix that for the next version. What should I put?

**Comment by ricardobarone** [comment]
That's great,

I'd recommend using the minimum version needed by angular-toastr, For example, if it's 1.3.0:
`"angular": ">=1.3.0"`
