### ISSUE TITLE
preventDuplicates doesn't allow to show same message after timeout

### ISSUE THREAD

**Issue by tsvtitan** [Foxandxss/angular-toastr#91]
Sometimes, It's necessary to show same message after timeout if there is no other messages in the list and preventDuplicates is true

**Comment by Foxandxss** [comment]
Why did you close it? I am merging a patch which will allow you to do what you want.

**Comment by tsvtitan** [comment]
I've already did. See workaround:
function shouldExit() {
        if (options.preventDuplicates) {
          if (map.message === previousToastMessage) {
            return toasts.length>0;
          } else {
            previousToastMessage = map.message;
          }
          return false;
        }
  }

**Comment by Foxandxss** [comment]
I merged #89 which has a good option for that, check it out. I will release 1.4.0 in a few minutes.

**Comment by tsvtitan** [comment]
Thank you!
