### ISSUE TITLE
Override positionClass for individual toastr didn't work

### ISSUE THREAD

**Issue by rvrv** [Foxandxss/angular-toastr#98]
Code below should display toastr on top with full width but it didn't

toastr.error('Login failed!', 'Error',{
positionClass: 'toast-top-full-width'
});

**Comment by Foxandxss** [comment]
No, it shouldn't.

Read the readme, the part of what can you override in a concrete toast and that is not one of them.

The position is not for a toast, the position is for the container who hosts the toasts. The toasts doesn't know anything about positions, they just appear on a container div and that container div is positioned somewhere.

When there is no toasts on screen, the container disappear so you could potentially change the position on the toastrConfig so the next created container will be in that position.

**Comment by rvrv** [comment]
thanks for clarifying.
